Introduce flag to disable build-tool-depends: alex
haskell/cabal pull request #10104
Opened 2024-06-12 09:12 UTC by alt-romes

In particular, this flag can then be used by `ghc` to provide source distributions that can be built using `ghc` only.

Fixes #10061

2024-06-12 16:11 UTC, geekosaur approved these changes

2024-06-13 03:14 UTC, geekosaur commented
Does this need to be backported?

2024-06-14 17:53 UTC, hololeap commented
96b95c337b5ec1262178e3687c5b97fda4becf1b worked for `ghc-9.10.1` on Gentoo (even after `alex` was removed) with the appropriate change to `hadrian.settings`:

```diff
+       # Disable need for alex util when building Cabal-syntax
+       echo '*.Cabal-syntax.cabal.configure.opts += --flag=no-alex' >> _build/hadrian.settings
```

2024-06-14 22:06 UTC, ulysses4ever approved these changes

2024-06-17 15:03 UTC, andreabedini requested changes
This needs further discussion.

Lexer.hs is not part of Cabal-syntax's source distribution, so alex has to be provided by whatever tool is orchestrating the build (cabal-install, hadrian, makefiles, etc)

2024-06-17 17:21 UTC, mpickering commented
> This needs further discussion.
> 
> Lexer.hs is not part of Cabal-syntax's source distribution, so alex has to be provided by whatever tool is orchestrating the build (cabal-install, hadrian, makefiles, etc)

I have clarified the situation here: https://github.com/haskell/cabal/issues/10061#issuecomment-2173695192

2024-07-02 08:46 UTC, Mikolaj commented
What shall we do with this ticket now that https://github.com/haskell/cabal/pull/10128 is merged?

2024-07-02 09:51 UTC, closed without merging

2024-07-02 09:51 UTC, alt-romes commented
#10128 is the better solution which makes this obsolete