Skip tasty 1.5.1
haskell/cabal pull request #10136
Opened 2024-06-22 21:50 UTC by geekosaur

Tasty 1.5.1, which was just released, is API incompatible with Tasty 1.5. Exclude it from build plans.

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

2024-06-22 21:51 UTC, geekosaur commented
Sorting out where it needs to be changed.

2024-06-22 22:47 UTC, geekosaur commented
I think that, since this may delay the release if we need to make fixes after the candidate goes up, we should skip the delay on this one.

2024-06-22 23:08 UTC, ulysses4ever requested changes
Why is the change for Mergify config a part of this PR?

2024-06-22 23:09 UTC, ulysses4ever commented
agree on skipping the delay btw

2024-06-22 23:10 UTC, geekosaur commented
Ugh, I thought I switched to `master` before making this branch. Lemme nuke it.

2024-06-22 23:18 UTC, geekosaur commented
Reverted `mergify.yml` to its state before the incorrectly incorporated commits.

2024-06-22 23:26 UTC, ulysses4ever reviewed
Thanks!

2024-06-22 23:27 UTC, ulysses4ever approved these changes

2024-06-23 00:43 UTC, geekosaur commented
Hm, commits still show as present, although a squash will fix that. Dunno if it's worth mangling the repo to fix.

2024-06-23 00:47 UTC, geekosaur commented
Okay, history is clean now.

2024-06-23 17:41 UTC, Kleidukos approved these changes

2024-06-23 17:41 UTC, Kleidukos commented
Cheers @geekosaur

2024-06-23 17:42 UTC, merged

2024-06-23 17:43 UTC, geekosaur commented
@mergify backport 3.12