Die if dynamic executable is requested on Windows
haskell/cabal pull request #10217
Opened 2024-07-19 14:17 UTC by jasagredo

Closes #9807

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

2024-07-19 18:06 UTC, geekosaur requested changes

2024-07-19 18:06 UTC, geekosaur commented on Cabal/src/Distribution/Simple/Errors.hs
> +      ++ ", does not support " ++ what
Fourmolu doesn't like this.
```suggestion
      ++ ", does not support "
      ++ what
```

2024-07-19 18:13 UTC, ulysses4ever approved these changes
Cool. thanks!

2024-07-22 21:46 UTC, Kleidukos commented
@jasagredo can you update this wiki page with a short paragraph on the Windows situation? https://gitlab.haskell.org/ghc/ghc/-/wikis/Linking

2024-07-22 21:47 UTC, geekosaur approved these changes
Not sure I'm an ideal reviewer given that I don't have a Windows install.

2024-07-22 21:48 UTC, jasagredo commented
> @jasagredo can you update this wiki page with a short paragraph on the Windows situation? https://gitlab.haskell.org/ghc/ghc/-/wikis/Linking

@Kleidukos I wish I could. I know that it doesn't work, but I don't know _why_ it doesn't work 😄

2024-07-22 22:05 UTC, Kleidukos commented
@jasagredo curse. Send me the paragraph and I'll integrate it. :)

2024-07-22 22:15 UTC, jasagredo commented
This is the only info I have https://gitlab.haskell.org/ghc/ghc/-/wikis/windows-dynamic-linking and maybe it is outdated, I don't know 😢

2024-07-26 00:09 UTC, merged