Make `cabal-testsuite` filterable with `--pattern`
haskell/cabal pull request #10427
Opened 2024-10-04 23:03 UTC by 9999years

This adds the `Tasty` `-p`/`--pattern` argument to the `cabal-testsuite` tests, making it possible to filter `cabal-testsuite` tests just like the other test suites:

    ./validate.sh -s build -s cli-suite -p HaddockKeepTmpsCustom

See also: #10425

2024-10-30 00:51 UTC, geekosaur approved these changes

2024-11-06 19:48 UTC, Kleidukos approved these changes

2024-11-06 21:53 UTC, ulysses4ever requested changes
The main point of documentation for this component is its README file. Could you, please, update it with information about this flag?

Are you aware that you can pass a filename as the argument? Your change seems to have similar purpose although I don't see what to do about it. The flag is more convenient, perhaps. But the old way is more well-known by the contributors, perhaps, so, as much as I like to cut down the code, it probably better stay there.

2024-11-08 19:05 UTC, 9999years commented
> @ulysses4ever The main point of documentation for this component is its README file. Could you, please, update it with information about this flag?

Done, thanks for the reminder!

> Are you aware that you can pass a filename as the argument?

Yes, but `validate.sh` runs `cabal-testsuite` from _within_ the `cabal-testsuite` directory, so it can't be passed paths relative to the repository root. This means that if I use `validate.sh -s build -s cli-suite --tasty-arg ...` to pass a test file directly, I can't tab complete it. (Also, of course, the paths tend to be rather long and annoying to type.)

> But the old way is more well-known by the contributors, perhaps, so, as much as I like to cut down the code, it probably better stay there.

Yes, absolutely! This change does not remove the ability to pass filenames directly. (I've double-checked that this is the case just now.)

2024-11-08 19:45 UTC, ulysses4ever approved these changes
Amazing, thanks!

2024-11-10 19:16 UTC, merged

2025-03-26 22:59 UTC, Mikolaj commented
@mergify backport 3.14