Deprecate `cabal format`
haskell/cabal pull request #10469
Opened 2024-10-17 21:35 UTC by jasagredo

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

2024-10-17 21:39 UTC, geekosaur approved these changes

2024-10-17 21:39 UTC, geekosaur commented on cabal-install/src/Distribution/Client/Main.hs
> +  hPutStrLn stderr "WARNING: `cabal format` is in process of deprecation, it will be removed in 3.16"
```suggestion
  hPutStrLn stderr "WARNING: `cabal format` is deprecated and will be removed in 3.16"
```

2024-10-17 21:40 UTC, jasagredo commented on cabal-install/src/Distribution/Client/Main.hs
> +  hPutStrLn stderr "WARNING: `cabal format` is in process of deprecation, it will be removed in 3.16"
Done, thanks! (very quick!)

2024-10-23 11:22 UTC, Mikolaj approved these changes
LGTM

2024-10-23 21:01 UTC, Kleidukos requested changes

2024-10-23 21:01 UTC, Kleidukos commented on changelog.d/pr-10469
> +significance:
This is a significant change, please add the `significant` metadata to this field.

2024-10-24 18:16 UTC, gbaz commented
I oppose this because we have had multiple projects in flight for years to get a working exact-printer format could make use of. I suppose once we get one, we can bring this command back done "right" but i don't see a point to this in the meantime... Just seems make-work for no reason?

2024-10-24 18:18 UTC, gbaz commented on cabal-install/src/Distribution/Client/Main.hs
>            [ newCmd CmdConfigure.configureCommand CmdConfigure.configureAction
by moving format from hidden to regular doesn't this make things worse, not better?

2024-11-07 20:07 UTC, ulysses4ever commented
I forgot to put this on the meeting agenda for today, sadly. Since it was meant to start with 3.14, it's a little tricky now that we don't seem to have a consensus, and the release is nearing. Any thoughts, @Kleidukos?

2024-11-12 07:51 UTC, jasagredo commented
What about not deprecating it in any way but for now adding a warning that says "this is not a proper formatter at the moment".

That way we don't deprecate the command but we tell the user to be cautious. Would that be ok for you @gbaz ?

2024-11-14 08:52 UTC, jasagredo commented
Closing this in favor of https://github.com/haskell/cabal/pull/10549

2024-11-14 08:52 UTC, closed without merging