Catch exception if git is not installed
haskell/cabal pull request #10486
Opened 2024-10-28 21:04 UTC by noiioiu

This is a trivial pr that should fix a bug in `cabal init` when `git` is not installed.

2024-10-28 21:10 UTC, geekosaur commented
Could you fill out one of the templates, please? I don't think this needs a changelog fragment, though.

2024-10-28 21:12 UTC, ffaf1 commented
I wonder if there is a way to test this automatically (if not, just user testing will do).

2024-10-28 21:14 UTC, geekosaur commented
Yes, I think for this one we want (very simple) manual QA notes.

2024-10-28 21:16 UTC, noiioiu commented
> Could you fill out one of the templates, please? I don't think this needs a changelog fragment, though.

Sure, do you have a link to the templates? I can't find them.

2024-10-28 21:17 UTC, geekosaur commented
https://github.com/haskell/cabal/blob/master/.github/pull_request_template.md

2024-10-28 21:21 UTC, geekosaur commented
Hm, building is failing https://github.com/haskell/cabal/actions/runs/11562678296/job/32184393856?pr=10486#step:6:1363

2024-10-28 21:40 UTC, geekosaur commented
That's not going to work because `m` isn't guaranteed to have access to `Exception` (`cabal init -n` doesn't). I _think_ you will have to arrange to run something like `"sh", ["-c", "git … || exit 0"]` and deal with the output being empty.

2024-10-28 21:52 UTC, noiioiu commented
Right, I don't think it's possible to define a MonadCatch instance for PurePrompt.

2024-10-31 00:29 UTC, ulysses4ever commented
> Yes, I think for this one we want (very simple) manual QA notes. I wouldn't trust trying to hide or remove git from a runner environment.

Why not? It should be as simple as the description of this PR shows: "simply" resetting the PATH. I think the testsuite might have a combinator for manipulating PATH. 

I don't want to block it for this reason, but having a regression test would be very valuable in this case.

2024-10-31 01:23 UTC, noiioiu commented
Added tests to the checklist. I'm not sure how or where to add the test though.

2024-10-31 01:26 UTC, ulysses4ever requested changes
Thanks for reporting and taking this on!

An integration test manipulating PATH can be found here: https://github.com/haskell/cabal/blob/63c486a1a65de599fa435c0cbf11ad85725f3c6c/cabal-testsuite/PackageTests/BuildTools/Foreign/setup.test.hs

General setup for integration tests is described here: https://github.com/haskell/cabal/blob/63c486a1a65de599fa435c0cbf11ad85725f3c6c/cabal-testsuite/README.md

Good luck!

2024-10-31 01:28 UTC, geekosaur commented
My worry with `$PATH` is that, on Linux at least, the part that needs to be removed is `/usr/bin`.

2024-10-31 01:34 UTC, noiioiu commented on cabal-install/src/Distribution/Client/Init/Types.hs
> +  maybeReadProcessWithExitCode a b c = Just <$> readProcessWithExitCode a b c
It should, the `readProcessWithExitCode` used in the definition of `maybeReadProcessWithExitCode`  is the same one defined on line 441, right?

2024-10-31 02:26 UTC, ulysses4ever commented on cabal-install/src/Distribution/Client/Init/Types.hs
> +  maybeReadProcessWithExitCode a b c = Just <$> readProcessWithExitCode a b c
oh, my bad!

2024-10-31 11:42 UTC, ulysses4ever approved these changes
Brilliant! 

Have you tried to run the test without your patch? That would be a good sanity check to see that it fails since it's a somewhat non-trivial test.

2024-10-31 15:14 UTC, noiioiu commented
> Brilliant!
> 
> Have you tried to run the test without your patch? That would be a good sanity check to see that it fails since it's a somewhat non-trivial test.

I ran it without the patch on a different branch (forked from 3.10) since I couldn't build `master` on my computer. It failed with the `posix_spawnp` error.

2024-10-31 15:32 UTC, geekosaur approved these changes

2024-10-31 15:32 UTC, Kleidukos commented
Assigning myself for manual QA once this lands on `master`

2024-10-31 15:39 UTC, noiioiu commented
> > since I couldn't build `master` on my computer.
> 
> Uh, what happened? Is this something likely to affect other people?

I think it might be because I was using cabal 3.10.3.0.

> I assume the `posix_spawn` is what we expect to see without the patch (as reported in #10484) --- that's great!
> 

Yes, it's the same error.

2024-10-31 15:47 UTC, geekosaur commented
Older `cabal-install` should be able to install newer ones, so that sounds like a bug. Please file a new issue including as many details about what you did and what happened as you can.

2024-11-06 03:33 UTC, merged

2024-11-06 03:34 UTC, ulysses4ever commented
@Mergify backport 3.14

2024-11-06 16:29 UTC, geekosaur commented
@mergify backport 3.12