Fix mistake in BuildInfo.Lens.hs
haskell/cabal pull request #10609
Opened 2024-11-29 04:02 UTC by andreabedini

```
  cxxSources f s = fmap (\x -> s{T.cSources = x}) (f (T.cxxSources s))
```
should be
```
  cxxSources f s = fmap (\x -> s{T.cxxSources = x}) (f (T.cxxSources s))
```

2024-12-02 02:42 UTC, andreabedini commented
> Template missing.

Guilty as charged. For a change this obvious and small, the mental effort required to process the template was higher than the one required to fix the bug. I mean no disrespect though.

2024-12-02 04:52 UTC, ffaf1 commented
No worries. This needs a changelog, does it not?

2025-03-13 10:40 UTC, Mikolaj requested changes
Yes, this does not look like an obvious exception from the changelog rule. But well spotted!

2025-04-10 17:58 UTC, Mikolaj commented
@andreabedini: a humble ping?

2025-07-01 14:59 UTC, ulysses4ever approved these changes
Good modulo draft state of the changelog, which I proposed how to fix.

2025-07-01 14:59 UTC, ulysses4ever commented on changelog.d/pr-10609
> +synopsis: Fix
```suggestion
synopsis: Fix mistake in BuildInfo/Lens.hs mixing up `c-sources` and `cxx-sources`
```

2025-07-01 15:08 UTC, geekosaur commented
Should we fast-track this just to get us to the 3.16 finish line faster?

2025-07-01 16:09 UTC, ulysses4ever commented
yes

2025-08-29 15:52 UTC, zlonast commented
@andreabedini I think it's time to rebase and add the `merge me` label :)

2025-08-29 16:00 UTC, geekosaur commented
Also it occurs to me that nobody noticed (cf. https://github.com/haskell/cabal/pull/10609#pullrequestreview-2469202289) because of https://github.com/haskell/cabal/pull/7072 and in general considerable confusion about `cc-options` vs. `cxx-options` that have only relatively recently been fixed, which would have masked it.

2025-08-29 16:02 UTC, geekosaur commented
@Mikolaj, can you re-review or at least dismiss your changes-requested now that the changelog entry has been added?

2025-08-30 05:48 UTC, Mikolaj approved these changes
Thank you very much!

2025-08-31 17:55 UTC, zlonast commented
@mergify rebase

2025-08-31 20:29 UTC, merged