Add `cabal get --only-package-description`
haskell/cabal pull request #5162
Opened 2018-02-24 00:06 UTC by hvr

With this option, 'cabal get' writes to the destination directory only the
package description already available locally in one of the repository
indices.

The basename of the file name written to inside the target directory is
the package-id rather than only the package name.

This is mostly based on #1977

Co-authored-by: Miëtek Bak <mietek@bak.io>

----

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2018-02-24 06:13 UTC, 23Skidoo commented
Looks all right on a first glance, but needs docs; this is the relevant manual section: https://cabal.readthedocs.io/en/latest/developing-packages.html#downloading-a-package-s-source

2018-02-24 08:24 UTC, hvr commented
@23Skidoo just asking for the changelog-entry, is this 2.2 material or post-2.2 ?

2018-02-24 09:56 UTC, 23Skidoo commented
I think it's low risk, we can merge  it into 2.2.

2018-02-24 10:00 UTC, hvr commented
@23Skidoo fwiw; I still need to get `--pristine` working -- `--index-state` already works out of the box, but `--pristine` doesn't yet.

2021-05-09 09:14 UTC, jneira commented
if this is still sensible I think pristine should be already working (I hope so, don't checked it)

2022-04-21 21:26 UTC, jneira commented
This needs a changelog entry and updating docs but the code looks good

2022-04-21 21:27 UTC, jneira approved these changes
This needs a changelog entry and updating docs but the code looks good

2022-04-21 21:28 UTC, jneira requested changes
oops

2022-07-03 18:04 UTC, jneira commented
Closing in favour of #8263, thanks all!

2022-07-03 18:04 UTC, closed without merging