WIP: Pass -optcxx for GHC >= 8.10
haskell/cabal pull request #7072
Opened 2020-09-14 18:13 UTC by ejconlon

Intends to resolve [this issue](https://github.com/haskell/cabal/issues/6421). 

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2020-09-14 18:29 UTC, phadej requested changes
We need tests.

Also "negative" tests, that cxx-options are not passed to C-files, and C-options to C++-files as mentioned in a comment in the issue. (For GHC >=8.10).

2020-09-14 18:48 UTC, ejconlon commented
Yep, let me see what I can do about tests. In the meantime, I verified that this fixes the issue as reproduced [here](https://github.com/ejconlon/ffi-repro) with GHC 8.8.4 and 8.10.2.

2020-09-14 19:07 UTC, ejconlon commented
@phadej would https://github.com/haskell/cabal/tree/master/cabal-testsuite/PackageTests be the right place to put test cases? I haven't found a suitable unit test suite for this, so I think the integration tests there are appropriate.

If so, I will put in two examples lifted from the repro, both configured with `cc-options: -D__TESTOPT_C__` and `cxx-options: -D__TESTOPT_CXX__`:
1. A project including C sources that will `#error` if `__TESTOPT_CXX__` is defined or `__TESTOPT_C__` is NOT defined
2. A project including C++ sources doing the opposite

Is that comprehensive enough?

2020-09-14 20:13 UTC, phadej commented
@ejconlon yes, `PackageTests` is the place for such things.

2020-09-14 21:06 UTC, ejconlon commented
@phadej I put in two `PackageTests`: `ForeignOptsC` and `ForeignOptsCxx`. Assuming I ran them right, they both pass for me under both compilers with this change. Both of them pass `cc-options` and `cxx-options` and assert that they only pick up CPP flags from the correct one. If we are running them with 8.8 and 8.10 in the CI matrix, then I think we are in good shape.

2020-09-14 21:09 UTC, ejconlon commented
(Also, if you're planning on doing another RC for 3.4 I would love to get this change picked in!)

2020-09-15 08:52 UTC, phadej commented
Perfectly we would backport that to `Cabal-3.2` (shipped with GHC-8.10), as far as I'm aware GHC-8.10.3 will definitely happen.

@bgamari should I prepare `Cabal-3.2.1.0`?

2020-09-15 08:56 UTC, phadej requested changes
Squash commits, that will help backporting.

Write in the commit message what you have written in the description. Also write

```
Fixes https://github.com/haskell/cabal/issues/6421
```

(I prefer explicit URL, not an abbreviated number, as it makes easy to click from `git log`).

2020-09-15 08:56 UTC, phadej commented on cabal-testsuite/PackageTests/ForeignOptsC/foreign-opts-c.cabal
> +cabal-version:       2.2
make a top directory for these tests, maybe `PackageTests/FFI/ForeignOptsC` and `..Cxx`. As you may notice, the top level is already quite crowded, lets not have individual tests there.

2020-09-15 19:04 UTC, ejconlon commented
(By the way, this is the second commit for which that Windows job flaked out with some handle error!)

2020-09-15 19:04 UTC, bgamari commented
> Perfectly we would backport that to `Cabal-3.2` (shipped with GHC-8.10), as far as I'm aware GHC-8.10.3 will definitely happen.
> 
> @bgamari should I prepare `Cabal-3.2.1.0`?

Yes, that would be great. Thank you1

2020-09-15 19:14 UTC, phadej commented
@ejconlon yes, windows jobs are flaky. Don't worry.

2020-09-16 11:09 UTC, merged

2020-09-24 08:17 UTC, phadej commented
Backported to 3.4 in https://github.com/haskell/cabal/pull/7074

2020-10-26 10:25 UTC, phadej commented
Backported to 3.2 in https://github.com/haskell/cabal/pull/7134