[WIP] Extensible Interface Directories
haskell/cabal pull request #7158
Opened 2020-11-10 14:25 UTC by JoshMeredith

WIP

2020-11-19 16:16 UTC, phadej requested changes
I'd rather not accept this yet. This is reasonable change on its own, but if GHC decides to not use this approach it will be unnecessary addition.

2020-11-19 16:16 UTC, phadej commented on Cabal/src/Distribution/Simple/Utils.hs
>  -- | This installs all the files in a directory to a target location,
The documentation is outdated with this change.

2023-05-17 06:21 UTC, Kleidukos commented
Marking this PR as draft :slightly_smiling_face:
Let's revive this when GHC adopts it.

2025-05-08 18:21 UTC, ffaf1 commented
Hello, I am going through old PRs to check whether they are stale.

If this PR is still “live”, write a comment and I will remove the `consider closing` label. Otherwise in ≃ 2 weeks this PR will be closed.

2025-06-05 17:10 UTC, closed without merging