Change echo to printf
haskell/cabal pull request #7169
Opened 2020-11-21 16:03 UTC by jaredforrest

The command echo behaves differently in different shells whereas printf is more portable. This means `runhaskell Setup register --gen-script` may generate a buggy script if there are escape sequences in the package description.

See [here](https://www.reddit.com/r/archlinux/comments/joj4rc/psa_haskelllens_package_broken_for_people_using/)
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2020-11-21 17:11 UTC, phadej commented
What you mean by more portable? Isn't `echo` a builtin in any `sh`-like shell?

2020-11-21 17:15 UTC, phadej requested changes
Add comment. Also add test. I suspect this is due some data which need escape and `echo -e`? Don't make further contributors guess why you use `printf`.

2020-11-21 20:31 UTC, jaredforrest commented
I have updated the original comment.

2020-11-23 20:13 UTC, phadej requested changes
> Add extra newline that echo prints by default

Suggest we need to add tests, a test which would fail without this change.

2020-11-23 22:37 UTC, jaredforrest commented
> > Add extra newline that echo prints by default
> 
> Suggest we need to add tests, a test which would fail without this change.

I've just realized the newline does nothing so I'll remove it

2020-12-27 02:26 UTC, jaredforrest commented
You'd need to add a test which first configures and builds a test-package. Then the package is registered and unregistered using the shell script in different shells (e.g. bash, dash, zsh) . The output of `ghc-pkg describe TestPackage` for each shell would be compared with a canonical output. The test-package description would also include some escape codes (\t \a \'). 

An example of the commands is as follows:
```
runhaskell Setup configure
runhaskell Setup build
runhaskell Setup register --gen-script
runhaskell Setup unregister --gen-script
```
 Then for each shell
```
*sh register.sh
diff $(ghc-pkg describe TestPackage) canonical-output
*sh unregister.sh
```
The register and unregister should not return any errors and the diff should be empty

2021-08-12 02:51 UTC, merged

2021-08-12 16:17 UTC, fgaz commented
This is still missing a comment about why printf is used and a changelog entry. @jaredforrest could you add them in a  new pr?