Include `cmm-sources` when linking shared objects
haskell/cabal pull request #7183
Opened 2020-11-26 22:46 UTC by bgamari

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [x] The documentation has been updated, if necessary.

FIxes #7182 by fixing inconsistent object sets used during linking of vanilla and shared object output.

2020-11-27 11:00 UTC, phadej commented
Should the test work on Windows? @Mistuke, are dynamic objects truly missing, or is there an issue with setup?

```
Perhaps you haven't installed the "dyn" libraries for package âbase-4.12.0.0â?
```

2020-11-27 11:09 UTC, phadej commented on Cabal/Distribution/Simple/GHC.hs
> +                                             [tmpDir </> x | x <- cObjs ++ cxxObjs]
This change is something else? We don't need `cmmObjs` nor `asmObjs` however?

2020-11-27 15:34 UTC, Mistuke commented
> Should the test work on Windows? @Mistuke, are dynamic objects truly missing, or is there an issue with setup?

No, sadly dynamic way is not supported on Windows. Table next to code makes it hard.. I still have it on my list of things to fix.

2020-11-27 16:54 UTC, phadej requested changes
> No, sadly dynamic way is not supported on Windows.

Then the new test should be skipped on windows. `skipIfWindows` (IIRC)

2020-12-02 18:54 UTC, closed without merging

2020-12-02 18:54 UTC, phadej commented
Please make PR against `master`, I'll backport them. I almost missed that again.