Removed obsolete warning about mixins in the doc
haskell/cabal pull request #7231
Opened 2021-01-08 22:09 UTC by danidiaz

The documentation for the "mixins:" field still featured an obsolete warning about a parsing bug which was solved in #5293 and #5292.

I have verified that it indeed works now.

Open issues about seemingly the same bug: #5150, #4864.

2021-01-14 11:14 UTC, fgaz commented
Same as the other pr, try rebasing

2021-01-15 10:15 UTC, phadej commented
Why this (and #7233) have cherry-picked commits from `master`? Is this something weird `git` did?

2021-01-15 14:55 UTC, danidiaz commented
@phadej I didn't cherry-pick, but I must have made a mess during the rebase.

2021-01-24 21:57 UTC, danidiaz commented
The rebase trouble should be fixed now, ditto for #7233.

2021-01-27 18:09 UTC, fgaz requested changes
The problem is fixed only for cabal-version (the .cabal spec) 3.0. For compatibility, it's still there when cabal-version is set to <3.0. Please write that in the note instead of deleting it

2021-02-15 14:14 UTC, danidiaz commented
Modified the note.

2021-02-15 16:55 UTC, fgaz approved these changes

2021-06-03 05:37 UTC, emilypi approved these changes

2022-02-12 21:42 UTC, jneira commented
@Mikolaj this is good to merge but ci is in a unfinshed state 🤔

2022-02-12 21:49 UTC, Mikolaj commented
@mergifyIO rebase

2022-02-12 21:52 UTC, Mikolaj commented
Let's see...

2022-02-12 22:37 UTC, jneira commented
oh i forgot about mergifiy, nice

2022-02-12 23:41 UTC, merged