Add changelog for #7413 (Fix instantiating an indefinite Backpack)
haskell/cabal pull request #7436
Opened 2021-06-08 23:30 UTC by ezyang

Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2021-06-09 08:02 UTC, Mikolaj approved these changes
Ritual performed correctly.

2021-06-09 17:40 UTC, emilypi approved these changes

2021-06-09 19:25 UTC, fgaz commented
@Mergifyio backport 3.6

2021-06-09 19:33 UTC, fgaz requested changes
I think this was purely a cabal-install change

2021-06-09 19:33 UTC, fgaz commented on changelog.d/pr-7413
> +packages: Cabal
```suggestion
packages: cabal-install
```

2021-06-09 19:33 UTC, fgaz commented on changelog.d/pr-7413
> +Previously, Cabal would always attempt to put instantiations of indefinite packages from Hackage in
```suggestion
Previously, cabal-install would always attempt to put instantiations of indefinite packages from Hackage in
```

2021-06-11 16:27 UTC, fgaz approved these changes
Thanks!

2021-06-11 16:29 UTC, merged