Include extra-lib-dirs-static into PackageHash
haskell/cabal pull request #7794
Opened 2021-11-03 11:11 UTC by alexbiehl

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2021-11-03 11:29 UTC, Mikolaj reviewed
Given that there's no test and, I assume, the main PR will be tested, could you add a changelog and mention there the main PR and/or main issue?

2021-11-03 11:49 UTC, jneira commented
We could add a test similar to the used one for check the fix for duplicate entries in package hash inputs: https://github.com/haskell/cabal/tree/master/cabal-testsuite/PackageTests/Regression/T6906

2021-11-08 14:59 UTC, Mikolaj commented
@alexbiehl: CI should run fine once you rebase --- I fixed the failure.

2021-11-15 20:59 UTC, Mikolaj commented
CI is green, we just need a minimal changelog file and test.

2021-11-29 10:13 UTC, Mikolaj commented
@alexbiehl: may I help you in getting this PR to the finish line? :)

2021-11-29 18:55 UTC, alexbiehl commented
> @alexbiehl: may I help you in getting this PR to the finish line? :)

I am sorry I didn't get to this. Help would be very much appreciated.

2021-11-29 19:05 UTC, alexbiehl commented
I also opened https://gitlab.haskell.org/ghc/ghc/-/issues/20759 upstream to track the GHC side of things.

2021-11-29 20:27 UTC, Mikolaj commented
Given that this is a part of #6935, the changelog.d/pr-7794 could be

```
synopsis: Include extra-lib-dirs-static into PackageHash
packages: cabal-install
prs: #7794
issues: #6935
```

2021-11-29 20:31 UTC, Mikolaj commented
> We could add a test similar to the used one for check the fix for duplicate entries in package hash inputs: https://github.com/haskell/cabal/tree/master/cabal-testsuite/PackageTests/Regression/T6906

@alexbiehl: I think a copy-paste of this test would be an acceptably cheap way of testing this functionality. What do you think? Would you add that?

2022-01-29 13:28 UTC, Mikolaj commented
@alexbiehl: ping?

2022-02-24 20:58 UTC, gbaz approved these changes

2022-03-14 11:54 UTC, jneira commented
> Given that this is a part of #6935, the changelog.d/pr-7794 could be
> 
> ```
> synopsis: Include extra-lib-dirs-static into PackageHash
> packages: cabal-install
> prs: #7794
> issues: #6935
> ```

hmm #6935 is a pr, no an issue, and #6935 does not have a clear linked issue, afaics so maybe we should remove `issues: #6935` from the changelog?

2022-03-18 21:58 UTC, jneira commented
@Mergifyio rebase master

2022-03-19 09:35 UTC, jneira requested changes
the pr looks good but needs a changelog entry and a test, thanks

2022-04-21 17:12 UTC, emilypi approved these changes

2022-04-21 17:12 UTC, emilypi commented
Changelog entry + tests should be added - approved otherwise

2022-10-19 18:41 UTC, Mikolaj commented
@mergify rebase

2022-11-11 19:22 UTC, Mikolaj commented
@alexbiehl: respectful ping?

2022-11-18 13:12 UTC, alexbiehl commented
Hi! I am not sure how to test this TBH. Also this is a bug fix for something that is not used by anyone rn so I am not sure it needs an entry in the changelog.

2022-12-15 09:26 UTC, Mikolaj commented
@alexbiehl: I hope we can meet in the middle. :D 

We require changelogs for anything that differs from last published version, regardless of how internal the things are (so only a fix of a bug introduced in devel version would not require a changelog, if it refrained from modifying any extra things). However, if the test is hard to do and the change is internal, I think we can risk it (more than usual) without a dedicated test.

BTW, if you could also smuggle into the PR the changelog fixup @jneira mentions in https://github.com/haskell/cabal/pull/7794#issuecomment-1066696116, that would be super-awesome.

2022-12-15 16:29 UTC, alexbiehl commented
@Mikolaj I did add the changelog entry as suggested by @jneira

2022-12-16 17:21 UTC, jneira approved these changes

2022-12-16 17:52 UTC, Mikolaj commented
@alexbiehl: feel free to add the trigger label: merge_me or merge_me+squash.

2022-12-17 11:31 UTC, merged

2022-12-17 11:41 UTC, Mikolaj commented
@alexbiehl: thank you once again. BTW. we now merge via the mergify labels: https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions, which prevents complicated merge histories such us the one you just created and give interested people 2 more days to look at the final code before it's (rebased and) merged.