Update examples that used BSD3 to BSD-3-Clause
haskell/cabal pull request #7942
Opened 2022-01-31 04:47 UTC by sekunho

The examples contain pre-SPDX identifiers which causes `cabal check`
to complain about it being an unknown SPDX license identifier.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2022-01-31 07:51 UTC, Mikolaj commented
Whoa, we have 284 occurences of `BSD3` in the code. I guess nothing else than `check` checks that (and it's only a warning?).

2022-01-31 07:52 UTC, Mikolaj approved these changes

2022-01-31 07:53 UTC, sekunho commented
Yeah I wasn't sure if I should modify the ones outside those examples, so I just left them alone for now. If someone could help point me to which ones are OK to modify then I'll gladly work on them too.

2022-01-31 08:03 UTC, Mikolaj commented
Wow, Cabal itself has this wrong licence. 

> Cabal/Cabal.cabal:license:       BSD3

```
~/r/cabal$ cd Cabal
~/r/cabal/Cabal$ cabal check
No errors or warnings could be found in the package.
```

How come?

2022-01-31 08:07 UTC, Mikolaj commented
I'd guess it's safe to modify all *except* those occurence that test that `cabal check` complains as it should and except the bit of code that suggests to replace BSD3 with BSD-3-Clause (`templates/SPDX.LicenseId.template.hs`) and except `Cabal/src/Distribution/PackageDescription/Quirks.hs` that should be just left alone.

2022-01-31 08:09 UTC, Mikolaj commented
And `Cabal/src/Distribution/SPDX/LicenseId.hs` and `Cabal/src/Distribution/PackageDescription/Check.hs`.

2022-01-31 08:10 UTC, Mikolaj commented
The latter probably explains whey `cabal check` doesn't complain, but I'm curious how you made it complain.

2022-01-31 08:14 UTC, Mikolaj commented
Oh, you probably have some ancient `cabal-version` specified in your .cabal file?

2022-01-31 08:18 UTC, sekunho commented
I made a tiny reproducible example here: https://github.com/sekunho/cabal-check-fail

```
[sekun@nixos:~/Projects/cabal-check-fail]$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 

[sekun@nixos:~/Projects/cabal-check-fail]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

`cabal` file

```
cabal-version:      2.4
name:               cabal-check-fail
version:            0.1.0.0
synopsis:

-- A longer description of the package.
-- description:
homepage:

-- A URL where users can report bugs.
-- bug-reports:
license:            BSD3
license-file:       LICENSE
author:             SEKUN
maintainer:         sekun@hey.com

-- A copyright notice.
-- copyright:
-- category:
extra-source-files: CHANGELOG.md

library
    exposed-modules:  MyLib

    -- Modules included in this library but not exported.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base ^>=4.14.3.0
    hs-source-dirs:   src
    default-language: Haskell2010

executable cabal-check-fail
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:
        base ^>=4.14.3.0,
        cabal-check-fail

    hs-source-dirs:   app
    default-language: Haskell2010

test-suite cabal-check-fail-test
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          MyLibTest.hs
    build-depends:    base ^>=4.14.3.0
```

I chose a version of cabal after SPDX was introduced.

2022-01-31 08:19 UTC, sekunho commented
I made a tiny reproducible example here: https://github.com/sekunho/cabal-check-fail

```
[sekun@nixos:~/Projects/cabal-check-fail]$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 

[sekun@nixos:~/Projects/cabal-check-fail]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

`cabal` file

```
cabal-version:      2.4
name:               cabal-check-fail
version:            0.1.0.0
synopsis:

-- A longer description of the package.
-- description:
homepage:

-- A URL where users can report bugs.
-- bug-reports:
license:            BSD3
license-file:       LICENSE
author:             SEKUN
maintainer:         john@example.com

-- A copyright notice.
-- copyright:
-- category:
extra-source-files: CHANGELOG.md

library
    exposed-modules:  MyLib

    -- Modules included in this library but not exported.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base ^>=4.14.3.0
    hs-source-dirs:   src
    default-language: Haskell2010

executable cabal-check-fail
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:
        base ^>=4.14.3.0,
        cabal-check-fail

    hs-source-dirs:   app
    default-language: Haskell2010

test-suite cabal-check-fail-test
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          MyLibTest.hs
    build-depends:    base ^>=4.14.3.0
```

I chose a version of cabal after SPDX was introduced.

2022-01-31 08:37 UTC, Mikolaj commented
Oh yes, you are right --- it's Cabal.cabal that has an old cabal-version and that's why `cabal check` doesn't complain.

Wow, and when I update the licence in Cabal.cabal, it complains.

So it's dependent on the cabal-version. 

In that case, I guess it's safe to only change those you proposed at the start. BTW, with what cabal-version would they be run, by default? What is the user most likely to use?

2022-02-04 15:24 UTC, Kleidukos commented
@Mikolaj I think version 3 is what people are most likely to use nowadays, and it's compatible with SPDX identifiers

2022-02-04 15:24 UTC, Kleidukos approved these changes
While there may be much more work to do in the future, let's not block this PR

2022-02-04 15:38 UTC, Mikolaj commented
Let's ride!

2022-02-04 15:39 UTC, fgaz requested changes
> While there may be much more work to do in the future, let's not block this PR

I think the examples should be consistent. @sekunho could you update `cabal-version` in those examples to 3.0 and check that there are no additional warnings?

2022-02-04 15:51 UTC, Mikolaj commented
@fgaz has a point: some of these cabal-versions are ancient so new licence formats might not work with them. I do hope other things in these sample configs work fine with new cabal-versions. If not, they would be a bad fit for the manual. so I hope somebody would have spotted that already.

2022-02-04 22:33 UTC, ptkato commented
Aye, at first I haven't realised, but for any `.cabal` file with `cabal-version < 2.2`, the examples should remain in their old state, either that or bump the `cabal-version` to some version `>= 2.2`.

2022-02-04 22:56 UTC, sekunho commented
> In that case, I guess it's safe to only change those you proposed at the start. BTW, with what cabal-version would they be run with, by default? What is the user most likely to use?

`cabal init --interactive` has `2.4` as the default

```
Please choose version of the Cabal specification to use:
   1) 1.10   (legacy)
   2) 2.0    (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2    (+ support for 'common', 'elif', redundant commas, SPDX)
 * 4) 2.4    (+ support for '**' globbing)
   5) 3.0    (+ set notation for ==, common stanzas in ifs, more redundant commas, better pkgconfig-depends)
Your choice? [default: 2.4    (+ support for '**' globbing)] 
```

Although I'm not sure what `stack` generates as the default. Should this be the new one in the examples, or do I stick with `2.2`? 

> Sorry for blocking this, but I think the examples should not be left in an inconsistent state. @sekunho could you update cabal-version in those examples to 3.0 (or [any that uses SPDX identifiers](https://cabal.readthedocs.io/en/3.6/file-format-changelog.html)) and check that there are no additional warnings?

Agh I hadn't realized that; thanks for pointing that out. Let me work on it.

2022-02-04 23:06 UTC, ptkato commented
> `cabal init --interactive` has `2.4` as the default

By the way, in latest master the default for `cabal init` is `3.0`.

https://github.com/haskell/cabal/blob/55ad63273ce4ed3962dd59d0eca80510dc3ddc87/cabal-install/src/Distribution/Client/Init/Defaults.hs#L70

2022-02-04 23:11 UTC, sekunho commented
Alright `3.0` it is. Thanks @ptkato!

2022-02-13 12:48 UTC, fgaz requested changes
As i wrote in the last review, please check that the examples do not give more errors/warnings than they did before, using `cabal check`. There currently are parse errors in the `cabal-version` fields.

2022-02-18 15:43 UTC, fgaz commented
Hmm, there is still a new warning about missing `default-language` fields... I'm not sure if adding it is worth it or if it's just noise

2022-02-22 20:30 UTC, jneira commented
@Mergifyio rebase master

2022-02-24 10:25 UTC, jneira commented
@Mergifyio rebase master

2022-02-24 10:28 UTC, jneira commented
Removing the merge me label until @fgaz rereview last changes in [d5d381c](https://github.com/haskell/cabal/pull/7942/commits/d5d381cabc178211160288af5bcb0eea8d919ecd)

2022-02-28 05:23 UTC, sekunho commented
Ok done. I also added the missing `default-language` field for old examples that gave that warning. There are other warnings about missing fields of descriptions, maintainers, and categories but this was there since before, and I don't know if there are any benefits to adding those in each example.

I summarized the changes in the commit message. Let me know if there's anything else to change/add/remove.

2022-02-28 07:18 UTC, Mikolaj commented
Great. So that's ready for @fgaz's review.

2022-03-02 22:15 UTC, fgaz approved these changes
Thanks for all the changes, looks good now!

> There are other warnings about missing fields of descriptions, maintainers, and categories but those were there since before, and I don't know if there are any benefits to adding those in each example.

I agree it's fine. As you wrote, they were already there, and it's only metadata

2022-03-03 19:42 UTC, merged