Derive Eq on DependencyMap
haskell/cabal pull request #8061
Opened 2022-03-24 09:36 UTC by joshleeb

This change derives the `Eq` type class on `DependencyMap` in the
`Distribution.Types` module.

Closes #7849

2022-03-24 10:08 UTC, jneira approved these changes
it is following the advice of our experts in #7849 so lgtm, thanks!

2022-03-24 12:16 UTC, Mikolaj requested changes
Looks good. Don't we need the tiny changelog file, though?

2022-03-25 08:59 UTC, Mikolaj approved these changes
Perfect.

2022-03-25 18:16 UTC, Mikolaj commented
Did CI get stuck?

2022-03-25 18:34 UTC, Mikolaj commented
Let me cancel it so that other PRs can get through.

2022-03-25 20:49 UTC, Mikolaj commented
@mergifyIO rebase

2022-03-25 21:55 UTC, merged