Add support for the 64-bit S390X architecure
haskell/cabal pull request #8065
Opened 2022-03-25 08:54 UTC by stefan-sf-ibm

So far only the 32-bit S390 architecture is supported. This patch also adds the 64-bit S390X architecture.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2022-03-25 09:01 UTC, Mikolaj requested changes
LGTM. Would you add a tiny changelog file?

2022-03-25 09:45 UTC, jneira commented
> LGTM. Would you add a tiny changelog file?

instructions here: https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog

2022-03-25 09:58 UTC, stefan-sf-ibm commented
Added a changelog file including a `packages` section. Thanks for the quick review :)

2022-03-25 10:08 UTC, Mikolaj approved these changes
10/10

2022-03-26 14:27 UTC, jneira commented
It seems sometests are checking some hash affected by arch values, i guess the hash should be updated but i would take a look to tests source code to confirm:
https://github.com/haskell/cabal/runs/5690009338?check_suite_focus=true#step:13:18

2022-03-29 05:59 UTC, gbaz approved these changes

2022-03-29 06:40 UTC, Mikolaj requested changes
Re-running the CI to make sure the problem stays.

2022-03-29 06:40 UTC, Mikolaj commented
@mergifyIO rebase

2022-03-29 11:53 UTC, stefan-sf-ibm commented
Had a look at the diff of the serialized strings and they differ:

```
ArchI386X86_64PPCPPC64SparcArmAArch64MipsSHIA64S390S390XAlphaHppaRs6000M68kVaxJavaScriptOtherArch
```

Updated the tests with new MD5 sums accordingly.

2022-03-29 12:52 UTC, Mikolaj approved these changes
LGTM. Thank you.

2022-03-29 14:35 UTC, merged

2022-03-31 10:06 UTC, Mikolaj commented
@mergifyIO rebase 3.6

2022-03-31 10:21 UTC, Mikolaj commented
@Mergifyio backport 3.6

2022-03-31 11:36 UTC, phadej commented
This should be reverted or quickly implemented properly. This changes cabal format, and it would be a lot better if known architectures set was dependent on `cabal-version` (it didn't change for a long tiime, so there wasn't need to do it).

If i make a small change:

```diff
 
+  if arch(s390x)
+    build-depends: base
+
```

current cabals (i.e. old ones when this is released) will complain:

```
Warning: The following errors will cause portability problems on other
environments:
Warning: Unknown architecture name 's390x'
Warning: Hackage would reject this package.
```

2022-03-31 11:48 UTC, Mikolaj commented
Uhoh. So we need to bump cabal-version now? And similarly on branch 3.6, unless we decide it's foolish to bump cabal-version in a point release?

2022-03-31 12:20 UTC, phadej commented
practically it's a bad idea to introduce `cabal-version: 3.8` support in `Cabal-3.6`, you'd need to port all changes. And you'd still need to adhere to PVP so Haskell interface of `Cabal` library cannot be changed. (adding a constructor to a public sum type is a breaking change).

2022-03-31 12:46 UTC, Mikolaj commented
@stefan-sf-ibm: how important is the official backport to you (note that quite possibly there will be no more 3.6 releases, so that would just stay on master branch of 3.6 and that's it; now it stays in the backport PR)?

2022-03-31 12:55 UTC, stefan-sf-ibm commented
@Mikolaj I think the implications are not worthwhile the hassle. Hoped this is an easy backport which makes life easier and not harder ;-) I would rather drop the backport then. Sorry for the noise.

2022-03-31 13:10 UTC, Mikolaj commented
OK, thank you. So it remains to check if we already have `cabal-version: 3.8` and, if not, add it, aping however it was done for previous versions and, in particular, making sure the S390X addition is gated behind the version IIUC.

2022-03-31 15:14 UTC, stefan-sf-ibm commented
I had the impression that `master` branch is 3.8 ready but I might be wrong. At least I see `CabalSpecV3_8` but not much more. Is that enough or do we need more?

2022-03-31 15:23 UTC, fgaz commented
@stefan-sf-ibm we still need gating, as @phadej wrote:

> it would be a lot better if known architectures set was dependent on cabal-version

2022-03-31 17:42 UTC, stefan-sf-ibm commented
Can you elaborate a little bit about that? I first thought you mean to add `#if MIN_VERSION_Cabal(3,8,0)` guards around the S390X additions, though, that does not work since the macro is not defined.

2022-03-31 17:51 UTC, Mikolaj commented
`git grep -30 CabalSpecV` shows many different tools to gate thing.s No idea which one to use, but perhaps there already is an architecture gated by some version in the code? Or some other feature similar to architecture?

2022-03-31 19:05 UTC, fgaz commented
> I first thought you mean to add #if MIN_VERSION_Cabal(3,8,0) guards around the S390X additions, though, that does not work since the macro is not defined.

Cabal features have to be enabled coditionally (at runtime) on the [package description version (cabal-version)](https://cabal.readthedocs.io/en/3.6/file-format-changelog.html). Specific versions of the package description specification are immutable, otherwise what @phadej mentioned in https://github.com/haskell/cabal/pull/8065#issuecomment-1084466947 would happen.

Here's an example of gating:

https://github.com/haskell/cabal/blob/ebfd8c7270dd603ddbf6ec5302a8145427f2763f/Cabal-syntax/src/Distribution/Types/Dependency.hs#L162-L170

2022-04-01 11:18 UTC, stefan-sf-ibm commented
So with known architectures we literally mean `knownArches :: [Arch]` not including the sum type `data Arch` (which in some sense enumerates the known architectures) which I would only know to guard at compile-time via CPP macros. In that regard what @phadej suggested is to change to something like `knownArches :: CabalSpecVersion -> [Arch]`. Usages of `knownArches` is in (beside a test case)

https://github.com/haskell/cabal/blob/ebfd8c7270dd603ddbf6ec5302a8145427f2763f/Cabal-syntax/src/Distribution/System.hs#L209

and

https://github.com/haskell/cabal/blob/ebfd8c7270dd603ddbf6ec5302a8145427f2763f/Cabal-described/src/Distribution/Described.hs#L346

2022-04-07 14:23 UTC, Mikolaj commented
@stefan-sf-ibm: I don't know this bit of code, but perhaps somebody on #hackage does. Do you need help with this issue?

2022-04-07 16:12 UTC, stefan-sf-ibm commented
@Mikolaj in order to understand the actual problem I tried to reproduce what @phadej described by adding

```
if arch(s390x)
    build-depends: base
```

to a local cabal project. Running `cabal build` on an s390x machine utilizing cabal version 3.2 the if condition evaluates to false whereas with my patch it evaluates to true. This was the expected output from my side.

A couple of years ago support for `AArch64` was added in commit fe9d70457a45d222c5b35f281d0c711d773e604c which looks pretty similar to my changes. Thus I'm still kind of puzzled what the actual problem is. It would be great if someone could point me to the right direction.

2022-04-07 17:05 UTC, gbaz commented
I think this is a good point -- cabal has _always_ accepted arches not explicitly enumerated, correct? It is simply the case that arches that are not enumerated are not handled well by cabal-the-library.

2022-04-08 11:35 UTC, Mikolaj commented
@phadej, what do you think?

2022-04-08 11:40 UTC, phadej commented
This feels unhygienic to me. Older `cabal-install` won't work with packages using `if arch(s390x)` while newer will without really telling why.

Not critical, but the fact it was done previously so doesn't mean it's a good way.

2022-04-08 16:44 UTC, gbaz commented
I don't see any reasonable thing to be done here. The If the cabal grammar accepts other arches, then there's no difference in grammar induced by this change -- it just makes cabal-the-library more able to handle effectively more of the allowed values.

In the future one might imagine changing the grammar to limit arches to only those known by particular versions of cabal, but this seems like it would induce additional headache for unclear benefit.

2022-04-15 16:04 UTC, Mikolaj commented
I'm sure we could somehow improve the situation, but we have bigger problems at hand and 3.8 is likely to be late (wrt GHC 9.4), so I recommend we close this. Oh, wait, it's closed. :)

@stefan-sf-ibm: thank you again!

2022-04-16 08:01 UTC, stefan-sf-ibm commented
Thanks everyone for sorting this out. Much appreciated. Looking forward to 3.8 release :)