Improve error message for empty --allow-newer= (fix #7740)
haskell/cabal pull request #8140
Opened 2022-05-14 03:22 UTC by ulysses4ever

This is a WIP, it's not beautiful:

```
❯ $CABAL build --allow-newer=                                                                                              1 (0.018s) < 04:31:50
Error: cabal: invalid argument to option `--allow-newer': "<parsecToReadE>"
(line 1, column 1):
unexpected empty argument list for --allow-newer=. Use --allow-newer without
the equals sign to permit all packages to use newer versions.
expecting "*"
```

Should `"parsecToReadE"` be removed? It can be but this may be make it harder to debug anything that goes via `parsecToReadE`. 

`expecting "*"` is annoying but I'm not sure how to remove it either.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2022-05-15 03:07 UTC, ulysses4ever commented
Okay, I think it's ready for review now. I found a way to extend the current approach for converting `ParsecParser` to `ReadE` that shouldn't break anyone's workflow, and at the same clean up the parsing error message:

```
❯ $CABAL build --allow-newer=                                                                                                    1 (0.029s) < 04:55:15
Error: cabal: invalid argument to option `--allow-newer': empty argument list
is not allowed. Note: use --allow-newer without the equals sign to permit all
packages to use newer versions.
```

I  didn't notice that error message form were tested anyhow. Have I missed it and should add a test? At the moment I'm not sure where to addit.

2022-05-15 03:10 UTC, ulysses4ever commented
Would appreciate if @phadej could take a look, as the parts of code I touched are mostly due to him.

2022-05-16 06:34 UTC, Mikolaj requested changes
A tiny changelog file would be needed nevertheless. LGTM otherwise. Congrats.

2022-05-17 08:28 UTC, Mikolaj approved these changes

2022-05-17 08:29 UTC, Mikolaj commented
CI got canceled. Let me try to restart.

2022-05-17 08:29 UTC, Mikolaj commented
@mergifyIO rebase

2022-05-17 13:08 UTC, Kleidukos approved these changes

2022-05-17 13:14 UTC, Mikolaj commented
No time to lose --- let's merge it (via merge_me label) before somebody says it doesn't make sense.

2022-05-17 13:16 UTC, Kleidukos commented
_Jetzt geht's los_

2022-05-17 13:16 UTC, merged