Add CI job testing only Cabal with the latest GHC
haskell/cabal pull request #8151
Opened 2022-05-19 14:00 UTC by andreabedini

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2022-05-19 14:02 UTC, Mikolaj approved these changes
That should help. Thank you.

2022-05-19 14:09 UTC, jneira commented on .github/workflows/validate.yml
> +          #
minor thing, an empty comment

2022-05-19 14:20 UTC, andreabedini commented
I am not sure this is doing what I expected, I only see one `ubuntu-latest ghc-9.2.1` rather than two. I should have included the cli flag in the job title.

2022-05-19 23:57 UTC, andreabedini commented on .github/workflows/validate.yml
> +            ghc: "9.2.1"
Yes but building Cabal and cabal-install together in a build plan will likely exclude new versions of the boot libraries through dependencies of cabal-install.

By the way. AFAIU elements of the build matrix don't have any specified semantic, so they should not get "collapsed" in any way. We had the tuple `(os: ubuntu-latest, ghc: 9.2.1, cli: null)` where `cli: null` gets interpreted as `true` in https://github.com/haskell/cabal/blob/a5309888fc0a33e511504c105907e8603a572143/.github/workflows/validate.yml#L109-L111 I am expecting this PR to add the tuple `(os: ubuntu-latest, ghc: 9.2.1, cli: false)`.

2022-05-20 14:00 UTC, jneira commented on .github/workflows/validate.yml
> +            ghc: "9.2.1"
aha, thanks for the explanation, could we add a comment about why we are building the same ghc twice?

2022-05-22 16:34 UTC, andreasabel requested changes

2022-05-22 16:34 UTC, andreasabel commented on .github/workflows/validate.yml
> +          # this is to build Cabal with boot packages form the lastest GHC
lastest -> latest

2022-05-22 16:34 UTC, andreasabel commented on .github/workflows/validate.yml
> +            ghc: "9.2.1"
This feels like a hack to me.  
It would be clearer if `cli: [true]` was added to the build matrix, imo.

2022-05-23 01:32 UTC, andreabedini commented on .github/workflows/validate.yml
> +            ghc: "9.2.1"
@andreasabel I agree. @jneira I hope you don't mind if I change that.

2022-05-23 02:04 UTC, andreabedini commented
I am thinking we should try a different approach here.

Our "validate" workflow should tests whether or not changes we make to the repo break the assumptions defined in the test suites.

Testing Cabal against the latest versions of the boot libraries is a completely different thing and should belong to a separate workflow.

If there's no objections, I will make a separate workflow that would run on a schedule (once a week?) and also on demand, that only builds Cabal. Does that sound right? (Btw, should I use `--allow-newer`?).

2022-05-23 06:40 UTC, andreasabel commented
> make a separate workflow that would run on a schedule (once a week?) and also on demand, that only builds Cabal. Does that sound right? 

That sounds very reasonable.

> (Btw, should I use `--allow-newer`?).

In my experience, a "all in" `--allow-newer` often leads to bad build plans, as very old versions of package might suddenly become candidates.  But using it selectively could be a useful tool.  (Maybe something like `--allow-newer='Cabal:*'` to restrict relaxation to `Cabal`'s dependency list only.)

2022-05-23 15:33 UTC, jneira commented on .github/workflows/validate.yml
> +            ghc: "9.2.1"
well, no other than being able to reverse the default behaviour only changing the condition iirc, but agree we could be more explicit here and use the variable directly to reverse it

2022-05-24 09:35 UTC, andreabedini commented
> Maybe something like `--allow-newer='Cabal:*'` to restrict relaxation to `Cabal`'s dependency list only

Oh yes, sorry, I absolutely meant that. Thank you for correcting me.

2022-07-03 21:18 UTC, jneira commented
> If there's no objections, I will make a separate workflow that would run on a schedule (once a week?) and also on demand, that only builds Cabal. Does that sound right? (Btw, should I use --allow-newer?).

But we should think in some way to make visible the fail, to fix it asap. Scheduled workflows fails are notified via github but maybe we would need another channel (email?)

2022-07-04 09:21 UTC, Mikolaj commented
> but maybe we would need another channel (email?)

Sending failures to all maintainers, with a possibility of opt-out, sounds a good idea to me.

2022-10-13 23:55 UTC, closed without merging