Preparation for 3.8.0.20220526 pre-release up to and including release notes
haskell/cabal pull request #8157
Opened 2022-05-23 16:53 UTC by Mikolaj

This is done by tracking the checklists at https://github.com/haskell/cabal/wiki/Making-a-release

Let's (revise and) merge this phase before we tackle the next (in particular, bootstrap and CI changes; I wonder if CI failes due to not being updated to new version on this branch; or perhaps it's going to pass voidly, testing a previous version).

2022-05-23 17:10 UTC, Mikolaj commented
Actually, the abruptness with which CI fails surprises me. What's going on? What should I update in GHA setup? Or should something in the github UI setting tab be changed?

2022-05-24 08:10 UTC, Mikolaj commented
CI seems stuck; let me push -f.

2022-05-24 08:12 UTC, Mikolaj commented
Hmm, it seems only the display was stuck, despite reloading the page. Now CI seems green for the previous push. \o/

2022-05-24 11:39 UTC, Kleidukos requested changes
no wait actually, I think the "BSD3" symbol is not a valid SPDX identifier. I think we're looking for BSD-3-Clause

2022-05-24 12:30 UTC, Kleidukos commented
> > no wait actually, I think the "BSD3" symbol is not a valid SPDX identifier. I think we're looking for BSD-3-Clause
> 
> Oh, nice catch. You mean, in the cabal files where I bumped cabal-version, I now need to adhere to SPDX as well, right? Will do.

Yeah, even if Cabal syntax version 2.0 doesn't complain, it's better to be future-proof

2022-05-24 13:20 UTC, Mikolaj commented
@Kleidukos: done in #8160. Will be backported (with lots of conflicts).

2022-05-24 16:15 UTC, Mikolaj commented
It turns out the "stuck CI" on 3.8 branch was just the outdated 3.* projection rules automatically applying to 3.8. I've updated them.

2022-05-24 17:49 UTC, Kleidukos approved these changes
beautiful

2022-05-24 19:01 UTC, ulysses4ever approved these changes

2022-05-24 19:10 UTC, Mikolaj commented on cabal-testsuite/cabal-testsuite.cabal
> +  setup-depends: Cabal == 3.6.*,
Yes, I don't understand it, either, it's something about Custom setup and I don't touch it with a pole. But a code dive for the exception I was getting (`ConstraintSetupCabalMaxVersion` or something related) got me to this conclusion, hence the comment. Could the comment be improved?

2022-05-25 01:06 UTC, ulysses4ever commented on cabal-testsuite/cabal-testsuite.cabal
> +  setup-depends: Cabal == 3.6.*,
I think it's fine. I guess I'd just make sure that it's also mentioned on the "Making the release" wiki page.

2022-05-25 07:57 UTC, Mikolaj commented on cabal-testsuite/cabal-testsuite.cabal
> +  setup-depends: Cabal == 3.6.*,
Indeed, thank you. Added to the wiki page.

2022-05-25 07:58 UTC, merged

2022-05-27 15:55 UTC, Mikolaj commented
To be honest, the change to [cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs](https://github.com/haskell/cabal/pull/8163/files#diff-2d425fcad95b791b03a5353137907a1db325888f72a6dcce123d172ab3cd8e32) would normally require a changelog, but given that it's a tiny fix, made on a branch, etc., let's be forgiving.