Remove warning on option -threaded when building libraries
haskell/cabal pull request #8432
Opened 2022-08-27 06:30 UTC by lyokha

Fixes #8431. Accompanied by option -flink-rts, option -threaded defines
the flavour of the ghc RTS library the built library will be linked
against. Note that bare ghc does not warn when option -threaded is used
for building a library either.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

2022-08-27 11:17 UTC, ulysses4ever approved these changes
Thank you!

2022-08-27 11:55 UTC, ffaf1 approved these changes
Very good, thanks for modifying test and adding an explanatory commit message.

2022-08-27 12:04 UTC, Mikolaj requested changes
We'd also need a minimal test and a tiny changelog file. Please yell if you encounter any trouble.

2022-08-27 12:14 UTC, ffaf1 commented
@Mikolaj by modifying the test *output*, I think we have a proper test (i.e., `-threaded` is present in `pkg.cabal`, and does not produce a warning).

2022-08-27 12:45 UTC, Mikolaj commented
> @Mikolaj by modifying the test _output_, he created a proper test (i.e., `-threaded` is present in `pkg.cabal`, and does not produce a warning).

You are right. So only tje little changelog file is pending.

2022-08-27 13:27 UTC, lyokha commented
I added a small changelog with mention that issue #774 can be regarded as a test for this PR. I alo added *\[ci skip\]* in the log message, not sure if this makes sense in this repository.

2022-08-27 13:55 UTC, lyokha commented
It looks that it was my mistake to put *[ci skip]* into the commit message: now the checks won't progress. I hope someone with admin privileges could start them manually.

2022-08-27 14:16 UTC, ulysses4ever commented
I was long curious as to what will happen with Mergify if we put [skip ci] on a commit --- thanks a lot for trying it out! The outcome is clear: it's not supported and leads to a stuck state. As to a way forward: I don't immediately see how to run CI manually. One solution would be to force-push an updated commit with no [skip ci] from your end.

2022-08-27 14:32 UTC, lyokha commented
@ulysses4ever, I'll try to force-push now. I am so glad to bring new knowledge :) (just kidding, I didn't mean to make this happen)

2022-08-27 16:45 UTC, Mikolaj approved these changes
10/10

2022-08-27 16:49 UTC, Mikolaj commented
@lyokha: I've invited you to the repo with initiation level Triage so that you can set label `merge_me` (or its squash variant), which in 2 days is going to get this commit merged.

2022-08-27 17:40 UTC, ulysses4ever commented
I'd suggest to use squash+merge for this one.

2022-08-30 17:15 UTC, Mikolaj commented
@mergify refresh

2022-08-30 17:20 UTC, Mikolaj commented
@mergify rebase

2022-08-30 17:22 UTC, Mikolaj commented
Mergify got stuck on a rule not matched and neither put this into queue nor rebased, so I'm rebasing manually. I hope I haven't over-reacted. Where could we see the queue, BTW?

2022-08-31 01:39 UTC, ulysses4ever commented
@Mikolaj 
> Where could we see the queue, BTW?

[In the dashboard](https://docs.mergify.com/actions/queue/#viewing-the-merge-queue).

2022-08-31 09:05 UTC, Mikolaj commented
> https://dashboard.mergify.com/github/haskell/repo/cabal/queues

Thank you. And the queue is currently empty, so it seems mergify waits another 2 days after either getting its rule applicability mixed up or just after a rebase? Let me merge manually in that case.

2022-08-31 09:05 UTC, Mikolaj commented
@mergify rebase

2022-08-31 09:08 UTC, merged

2022-08-31 09:08 UTC, Mikolaj commented
I've squashed, according to @lyokha's preference. Thank you all!