don't send non-extant extra-lib-dirs to ghc #6492
haskell/cabal pull request #8510
Opened 2022-10-03 16:44 UTC by gbaz

* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] Test

2022-10-24 18:06 UTC, Mikolaj commented
@gbaz: is this ready for review?

2022-10-26 15:27 UTC, Mikolaj commented
Hey, why is there no label, in that case? :)

2022-10-26 15:29 UTC, Mikolaj reviewed
This seems safe (famous last words). Is there a cheap way of protecting this PR from accidental reversion via a test?

2022-12-09 13:51 UTC, Ericson2314 commented
Should `extra-include-dirs` be handled in the same way for consistency? I don't love making an ad-hoc policy to work around what's arguably a GHC bug, but if we do this everywhere then it's not ad-hoc? :D

2022-12-24 08:57 UTC, Kleidukos approved these changes

2023-01-02 12:01 UTC, andreasabel requested changes
I wonder about the placement in `Distribution.Simple.GHC`.  Is this something GHC specific or shouldn't these non-existing directories be filtered out earlier in the pipeline, like after parsing?
Also, I agree with @Ericson2314 's concern that non-existing include directories should also be filtered out.

2023-01-02 19:31 UTC, andreasabel approved these changes
Fine with me.

2023-01-02 19:34 UTC, andreasabel commented on changelog.d/pr-8510
> +synopsis: don't send non-extant extra-lib-dirs to ghc
Didn't know that _non-existent_ can be condensed into _non-extant_ ... Now I know...

2023-01-02 19:42 UTC, andreasabel commented
@Mikolaj : I can't remember whether the policy was to (a) squash  the commit with the changelog into one commit with the feature or (b) to keep it separate.  
I guess (a), but feel free to change the label if (b) is the rule.  The contributor guide softly recommends (a): https://github.com/haskell/cabal/blob/7babda92df9e005185e7c9d5e9308a8a96092d7c/CONTRIBUTING.md?plain=1#L240-L242

2023-01-03 07:39 UTC, Mikolaj commented
> The contributor guide softly recommends (a)

I think it may be recommending it only because squashing requires one more mental action and users may need the nudge. If commits are well made (each one compiles, they separate refactorings from changes, etc.), as opposed to a string of fix-up commits, IMHO it's beneficial to retain them, including the changelog commit.

2023-01-03 07:39 UTC, Mikolaj commented
Ultimately it's up to the user and, normally, the users sets the label.

2023-01-03 07:40 UTC, Mikolaj commented
Doh, not user, but dev, PR author.

2023-01-03 09:14 UTC, andreasabel commented
> > The contributor guide softly recommends (a)
> 
> I think it may be recommending it only because squashing requires one more mental action and ~users~ devs may need the nudge. If commits are well made (each one compiles, they separate refactorings from changes, etc.), as opposed to a string of fix-up commits, IMHO it's beneficial to retain them, including the changelog commit.

You could add something like this to `CONTRIBUTING.md`.

2023-01-03 09:50 UTC, Mikolaj commented
> You could add something like this to CONTRIBUTING.md.

I'd like to keep CONTRIBUTING.md short and not (too much) opinionated. Perhaps just reduce the nudge? Or focus it on the most obvious case?

"If your pull request consists of several fix-up commits (not every commit compiles or they just don't help in understanding the PR, e.g., by separating formatting, refactoring and real functionality changes), please use `squash+merge me` instead of `merge me`..."

2023-01-03 16:16 UTC, ulysses4ever commented
I think we should lean to squashing unless the different commits are really different changes. (a) it makes for a clearer history (I doubt anyone benefits from tens or hundreds of commits "add changelog"), (b) individual commits are not tested by the ci, only the overall PR is, isn't it? in that case, there may be unbuildable "middle" commits that will severely complicate any future `git-bisect`ing.

2023-01-03 21:55 UTC, Mikolaj commented
Right, different trade-offs and tastes. Given that the PR page retains the original commits, I'd not worry about separating formatting, refactoring and (multiple) changes. However, we may want to migrate off github in the future and I'm can't be sure the PR commits are going to be migrated as well (given that the branch is deleted). Perhaps let's leave it as is. :)

2023-01-06 01:25 UTC, merged