Fix #8654: no assertion warning on special modes (help, version, etc.)
haskell/cabal pull request #8647
Opened 2022-12-30 12:33 UTC by andreasabel

Fix #8654: no assertion warning on special modes (help, version, etc.); print warning to `stderr`.

This PR moves the `warnIfAssertionsAreEnabled` until after the main command line argument parsing, and then only prints it on regular operation, i.e. not when just the help or version of cabal was demanded, or the command line could not be parsed.

Further, the warning is printed on stderr.  The previous attempt to use `warn` does not work as expected, as the verbosity aperatshnik isn't in place yet, so the warning cannot be suppressed by -v0.

Drive-by-shooting: straighten the convoluted control flow involving `maybeScriptAndArgs`.  This IO computation was invoked "brutto" before, when it is actually only needed in *one* branch of the case distinction.

2022-12-30 13:25 UTC, Mikolaj approved these changes
A nitpick: the refactoring and the functionality change would ideally be in separate commits.

2022-12-30 15:01 UTC, SaadAhmedGit commented
Shouldn't the warning message be:

> "**Warning:** this is a debug build of cabal-install with assertions enabled."

instead of
> "this is a debug build of cabal-install with assertions enabled."

Since the string "Warning: " was being prepended to the message automatically with `warn` which has now been removed thus, requiring the word to be written explicitly in the message. At least, it was that way when it printed to `stdout` before using `warn`.

2022-12-30 15:08 UTC, ulysses4ever commented
If the reason for doing away with `warn` is that -v0 is not parsed yet, maybe `warnIfAssertionsAreEnabled` could be pushed even further, to the point where -v0 is parsed and the verbosity machinery is up?

2022-12-30 19:52 UTC, SaadAhmedGit commented on cabal-install/main/Main.hs
>        "this is a debug build of cabal-install with assertions enabled."
prepend "Warning: " to the message

2022-12-30 19:55 UTC, SaadAhmedGit requested changes

2022-12-30 19:55 UTC, SaadAhmedGit commented on cabal-install/main/Main.hs
>        "this is a debug build of cabal-install with assertions enabled."
Prepend "Warning: " to the message.

2022-12-30 21:17 UTC, jneira commented
Thanks for the fix, it makes sense to not warn on those commands. Some chance of having a test for this?

2022-12-30 21:50 UTC, Mikolaj commented
Ouch, from all this enthusiasm, I forgot to ask for a test and a changelog file.

2023-01-02 11:32 UTC, andreasabel commented
> Ouch, from all this enthusiasm, I forgot to ask for a test and a changelog file.

Test: It seems we didn't have a test for this in the first place, otherwise it would have been broken by this PR.  What kind of test do you imagine for this?  Does CI run on tests on a `cabal-install` with assertions on?  Which test would be a model for the test envisioned here?

Changelog: I think this should not go into the changelog, as it does not affect regular users of `Cabal` and `cabal-install`.  If I am not mistaken, assertions will be off when building from Hackage...

2023-01-02 12:41 UTC, Mikolaj commented
> Test: It seems we didn't have a test for this in the first place, otherwise it would have been broken by this PR.

Indeed, that's strange.

> What kind of test do you imagine for this? Does CI run on tests on a `cabal-install` with assertions on?

CI definitely should run only with assertions on. But perhaps it calls cabal-install commands via some internal API bypassing the warning printout? I think we should have at least one test where the `cabal-install` binary is called directly (on one of the commands that trigger the warning)/

> Which test would be a model for the test envisioned here?

There may not be one.

> Changelog: I think this should not go into the changelog, as it does not affect regular users of `Cabal` and `cabal-install`. If I am not mistaken, assertions will be off when building from Hackage...

Yes, assertions are off on Hackage. This is debatable (changelog is useful for all consumers of cabal, including devs and bug reporters, the latter of which get confused most easily by the failed asssertions when reproducing with master branch artifacts from GHA), but I won't insist.

2023-01-02 13:32 UTC, andreasabel commented on cabal-install/main/Main.hs
>        "this is a debug build of cabal-install with assertions enabled."
Good, catch @SaadAhmedGit , fixed this.

2023-01-02 13:34 UTC, andreasabel commented
@ulysses4ever :
> If the reason for doing away with `warn` is that -v0 is not parsed yet, maybe `warnIfAssertionsAreEnabled` could be pushed even further, to the point where -v0 is parsed and the verbosity machinery is up?

It seems pushing this further in would require to prepend it to _every_ command.  I only pushed it as far in so that it is still before we branch into the individual commands.

2023-01-02 13:36 UTC, andreasabel commented
@Mikolaj: Ok, I added a changelog.

PR needs **SQUASHING** to integrate this into the main commit.

2023-01-02 13:46 UTC, Mikolaj commented
> @Mikolaj: Ok, I added a changelog.

Thank you.

> PR needs **SQUASHING** to integrate this into the main commit.

I think, if you set the label already, it will get squashed at the right time (meaning, after reviews and 2 days).

2023-01-02 13:57 UTC, SaadAhmedGit reviewed
LGTM

2023-01-02 13:57 UTC, SaadAhmedGit approved these changes

2023-01-02 16:54 UTC, ulysses4ever commented
@andreasabel 

> It seems pushing this further in would require to prepend it to every command.

But it means, then, that `-v0` is handled in every command? I hoped it's not the case. If it is, maybe a refactoring pulling it up would make sense, and that would allow to push the assertion message after it still?

2023-01-02 19:28 UTC, andreasabel commented
> @ulysses4ever wrote:
> But it means, then, that `-v0` is handled in every command? I hoped it's not the case. If it is, maybe a refactoring pulling it up would make sense, and that would allow to push the assertion message after it still?

Artem, please have a look at https://github.com/haskell/cabal/blob/7babda92df9e005185e7c9d5e9308a8a96092d7c/cabal-install/main/Main.hs and observe the amount of code duplication there.  I think refactoring this is a noble goal, but too much to require for this modest PR.

2023-01-02 21:28 UTC, ulysses4ever commented
@andreasabel fair enough!

2023-01-02 21:28 UTC, ulysses4ever approved these changes

2023-01-02 22:29 UTC, jneira commented
> Test: It seems we didn't have a test for this in the first place, otherwise it would have been broken by this PR.

That is just the core of the problem (a general problem in the cabal codebase) and no a valid argument to no add them imho
But to be fair if the tested cabal executable has no assertions, it is difficult to add them

2023-01-03 07:44 UTC, Mikolaj commented
> if the tested cabal executable has no assertions, it is difficult to add them

I think we might have had this discussion long ago, but I don't remember the conclusions. Naively, I'd think we should only ever test binaries with assertions. Perhaps one odd test without assertions to make sure no functional code got inserted into an assertion by mistake.

And indeed a quick look at `cabal.project.validate` turns up `-fno-ignore-asserts`. What's your evidence we test without assertions?

2023-01-05 09:26 UTC, merged