Refactor `cabal-install` solver config log output
haskell/cabal pull request #9159
Opened 2023-08-03 15:31 UTC by yvan-sraka

This PR does not modify `cabal` behaviour and is about code refactoring. It's part of the initiative described in this RFC https://github.com/haskell/cabal/issues/8939.

Special thanks to @andreabedini for refactoring and authoring the `displayMessage'` function. This significantly enhanced the readability of `Distribution.Solver.Modular.Message`. Moreover, the pair-programming sessions were invaluable in helping me kick off the implementation of a PATCH to address this issue :)

**Checklist:**

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

2023-08-04 09:47 UTC, michaelpj commented
Can you show us some examples?

2023-08-29 07:19 UTC, yvan-sraka commented
I've reworked the commit message a bit:

```
[WIP] Fix #4251: Simplify verbose "rejecting" message in solver

This commit makes the following changes:

- Enhancements to the codebase:
  * Adds several TODO/FIXME/HELP comments, laying the groundwork for
    improved solver output as described in issue #8939 ;
  * Refactors the `showMessages` function to split the logic of
    building the output (now as a `Message'` enumeration) and the
    string representation of it (now formatted by `displayMessage'`).

- Modifications to the solver output:
  * If the `-v3` or `--minimize-conflict-set` flags are not set, it
    now prompts the user to consider using them in cases of the
    "Could not resolve dependencies: ..." error ;
  * The message "(has the same characteristics that caused the
    previous version to fail: ...)" has been rephrased to
    "all other available packages. They are excluded due to the same
    constraint that caused the last version attempted to fail: ..." ;
  * Package lists are now grouped by name. For example, instead of
    displaying `aeson-1.0.2.1, aeson-1.0.2.0, aeson-1.0.1.0, ...`, it
    now shows `aeson: 1.0.2.1, 1.0.2.0, 1.0.1.0, ...`.
```

Before the changes …

```
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: hello-1.0.0.2 (user goal)
[__1] next goal: base (dependency of hello)
[__1] rejecting: base-4.16.4.0/installed-4.16.4.0 (conflict: hello => base>=5)
[__1] skipping: base-4.18.0.0, base-4.17.2.0, base-4.17.1.0, base-4.17.0.0,
base-4.16.4.0, base-4.16.3.0, base-4.16.2.0, base-4.16.1.0, base-4.16.0.0,
base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0, base-4.14.1.0,
base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (has the
same characteristics that caused the previous version to fail: excluded by
constraint '>=5' from 'hello')
[__1] fail (backjumping, conflict set: base, hello)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: hello, base
```

… and after the changes:

```
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: hello-1.0.0.2 (user goal)
[__1] next goal: base (dependency of hello)
[__1] rejecting: base-4.16.4.0/installed: 4.16.4.0 (conflict: new package does
not match existing constraint hello => base>=5)
[__1] skipping: all other available packages. They are excluded by the same
constraint that caused the last version tried to fail:
excluded by constraint '>=5' from 'hello'
[__1] fail (backjumping, conflict set: base, hello)
For detailed error messages, please rerun with the `-v3' flag.
To improve the solver output, consider running with the
`--minimize-conflict-set' option.
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: hello, base
```

There are many open questions left as code comments. I would greatly appreciate any feedback on them :)

2023-08-29 08:09 UTC, michaelpj commented
> all other available packages

Could this perhaps say "all other available versions of package <package>"? We're not rejecting _other packages_ and now the message doesn't tell us which package it is talking about, so when it later references a constraint it is unclear what it refers to.

2023-08-30 08:34 UTC, michaelpj commented
Also, if we run with higher verbosity we should perhaps go back to listing all the package versions that get rejected.

Alternatively, I wonder if we could do something more like footnotes, e.g. with verbose output produce
```
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: hello-1.0.0.2 (user goal)
[__1] next goal: base (dependency of hello)
[__1] rejecting: base-4.16.4.0/installed: 4.16.4.0 (conflict: new package does
not match existing constraint hello => base>=5)
[__1] skipping: all other available packages (1). They are excluded by the same
constraint that caused the last version tried to fail:
excluded by constraint '>=5' from 'hello'
[__1] fail (backjumping, conflict set: base, hello)

(1): base-X, base-Y, ...
```
Or maybe we even print this on normal verbosity (i.e. max of two additional package versions, then an ellipsis) and then print the full list only with higher verbosity.

2023-08-30 08:39 UTC, grayjay commented
Thanks for working on the solver error messages. I haven't had time to read the code carefully yet, but I have a few comments.

- It looks like this PR combines multiple independent improvements, so I think it would be better to split them into separate PRs. It would also help to split the `displayMessage'` refactoring into its own commit or PR that doesn't change behavior.
- I think that we should add a dedicated flag for showing better solver output (if it's too expensive to show it by default), rather than suggest that users rerun with -v3. -v3 shows maximum detail for debugging, such as multiple runs of the solver with `--minimize-conflict-set`, which isn't always helpful for users that are trying to understand conflicts.
- I'm not sure we should change the logic for suggesting `--minimize-conflict-set`. It is very unlikely to improve the solver output for small conflict sets.
- I'm not sure I understand the change to the message "has the same characteristics that caused the previous version to fail". The new message seems to be much more specific, so I don't think that it is correct in all cases. Maybe this PR should add a special case for when one version of a package is rejected by an existing version constraint, and then one or more of the following versions are rejected by the same constraint, as in the example with `base` above. That is a very common case, so I think that it is worth giving it a better message.

2023-09-14 08:28 UTC, andreabedini commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +
Do you think it's possible to separate the part of this function that applies the `goPReject` and `goPSkip` special handlers to the part that applies `displayMessage` to all messages? They are separate concerns and that is why we where doing this refactor (IIRC).

2023-09-14 08:29 UTC, andreabedini commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +-- The point would be to highlight the conflict in solver output:
Ideally any user-facing pretty-printing should be done in `cabal-install` and not in `cabal-install-solver`

2023-09-14 09:33 UTC, maralorn commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +
The last part might be an option.^^ Also you can always look at it and try reimplementing. I have been thinking about factoring out the graph layout algorithm from nom but it wouldn’t be trivial.

2023-10-23 10:19 UTC, yvan-sraka commented
I've reworked this PR a bit: It now aims to add a `--json` flag _(though I'm uncertain about the name)_ to the solver configuration arguments _(this is the last part currently not implemented)_. This allows the `cabal-install` solver's log output to be mechanized via an [external command](https://github.com/haskell/cabal/pull/9063), e.g., similar to the tree view that [`nix-output-monitor`](https://github.com/maralorn/nix-output-monitor) provides for `nix-build --log-format internal-json -v`. 

It would be greatly appreciated if this PR could receive another round of reviews, as it significantly refactors the solver logging logic: Instead of relying on strings, it introduces a new data structure representation of logs that's utilized in several places in the code before being serialized with `show`. 

I'm seeking advice on:
- what's the best method to serialize this data structure into JSON (should I just use [`aeson`](https://hackage.haskell.org/package/aeson)?)
- how to introduce a new user-facing solver configuration parameter in the CLI without having to modify a significant amount of code…

2023-10-24 02:34 UTC, andreabedini commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +
I guess this can be done another time.

2023-10-24 02:55 UTC, andreabedini commented
There are TODOs and clean ups left to do, but I think this is looking great. The solver is now giving structured information (`SolverTrace`) and cabal can take that information and give it to the user in the desired format.

`SolverTrace` has also a `Show` instance that replicates exactly how the solver was rendering its trace before so this is a drop-in replacement that should not cause any unintended change.

@yvan-sraka

> what's the best method to serialize this data structure into JSON (should I just use [`aeson`](https://hackage.haskell.org/package/aeson)?)

for serialising JSON we already have `Distribution.Client.Utils.Json`.

> how to introduce a new user-facing solver configuration parameter in the CLI without having to modify a significant amount of code…

Right, this hits the legacy parsing path for ProjectConfig but we can hope be able to avoid the worst of it. I'd start by following another solver flag like `--strong-flag` and adding this `--solver-log-format` (WDYT? mimicking nix's flag name) next to it. If I am not mistaken, this gets parsed in `Client.Setup` and converted to `ProjectConfigShared` by `convertLegacyAllPackageFlags`. The same flag has to be added to `ProjectConfigShared` as well, again following what is done for the other ones.

I hope this helps :crossed_fingers:

2023-10-31 07:03 UTC, grayjay reviewed
I read the updated diff, and I'm not sure I completely understand the PR. It looks like it currently has two main parts, the refactoring to add an intermediate representation of the solver log and a --json flag.

#### --json flag

What is the reason for formatting the log as JSON? Is it related to making the log collapsible as in #9199? I'm still not sure I understand the use case for collapsing it. Do you want to collapse the error message that is shown by default when the solver fails to find a solution, or the full verbose (-v3) log? Do you have an example of a build where it would have helped? I'm also curious to see an example because if a subtree seems irrelevant, it's possible that the solver didn't need to explore it, and it could be optimized away.

#### Refactoring

I can see how the `SolverTrace` data structure is useful for implementing different types of formatting, such as JSON or bolded output, but I was wondering if you were also planning to use it for other parts of #8939. If so, how would `SolverTrace` be used to change the contents of error messages?

This is the way that I understand the current code for creating the solver log:

The solver traverses the search tree and converts it to a list of `Message` in the `backjumpAndExplore` function. The list of `Message` aims to preserve as much of the tree structure as possible, without using a large amount of memory, by describing going up and down the branches of the tree. Then the solver uses the remaining tree structure to convert the `Message`s into strings that are more helpful for the user in `showMessages`, for example, by combining similar rejected versions into a single line.

I would expect that it would be better to apply most processing of the contents of the log to the list of `Message`s, where more of the tree structure is available.

2023-11-23 11:09 UTC, yvan-sraka commented
To answer @grayjay concerns, I decided to split this PR into two, this one now does only the refactoring, and it’s no longer a draft (I also updated the PR description).

The other one https://github.com/haskell/cabal/pull/9465, still a draft, will add the `--solver-log-format internal-json -v` option and so modifies the `cabal-install` CLI behavior, and I try to best continue the design discussions there.

Since I feel that part of the answer to your questions was in my comments: https://github.com/haskell/cabal/pull/9159#issuecomment-1774875820 and https://github.com/haskell/cabal/pull/9199#issuecomment-1731487440. I will write up in the original RFC https://github.com/haskell/cabal/issues/8939 an up-to-date plan of action of what I’m trying to achieve. Hope it will make the whole thing more sense :)

2023-11-30 03:56 UTC, grayjay commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +data Log
It would help to have some comments describing how the new types and `Message` relate to each other.

2023-12-19 11:54 UTC, yvan-sraka commented
I moved the fix to #4251 into https://github.com/haskell/cabal/pull/9541 (so the name of this branch is no longer accurate, but anyway that's best to keep the conversation here focus on the refactoring)! Thanks again @grayjay for your full review, I've tried to address most of your comments :)

2023-12-23 06:33 UTC, grayjay requested changes
@yvan-sraka Thanks! I still had some questions and comments from my last review, but they were collapsed due to the renaming changes, so I marked them with new comments to make them visible again. I also added a few comments on the new changes.

2023-12-23 06:33 UTC, grayjay commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +-- | Transforms the structured message type to actual messages (SummarizedMsg s).
The type name should be `SummarizedMessage`.

2023-12-23 06:33 UTC, grayjay commented on cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
> +    SummarizedMessage(..),
I don't think that `SummarizedMessage` needs to be re-exported from this module.

2025-06-07 03:20 UTC, sebright commented
Closing in favor of #10854.

2025-06-07 03:20 UTC, closed without merging