Add deprecation warnings to Nix integration
haskell/cabal pull request #9205
Opened 2023-08-25 10:21 UTC by yvan-sraka

This PR modifies `cabal` behavior by adding deprecation warnings to [Nix integration](https://cabal.readthedocs.io/en/latest/nix-integration.html). 

**Checklist:**

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.

Bonus points for added automated tests!

2023-08-25 10:36 UTC, ffaf1 approved these changes
Very good.

2023-08-25 10:54 UTC, Kleidukos requested changes

2023-08-25 10:54 UTC, Kleidukos commented on cabal-install/src/Distribution/Client/Nix.hs
> +      print "You can learn more about it here: https://cabal.readthedocs.io/en/latest/nix-integration.html"
You can actually use `warn verbosity "msg"` instead of print! :) This way it integrates better with the verbosity of cabal-install

2023-08-25 10:54 UTC, Kleidukos commented on cabal-install/src/Distribution/Client/Setup.hs
> +              "[DEPRECATED] Nix integration: run commands through nix-shell if a 'shell.nix' file exists (default is False)"
Very good, thank you.

2023-08-25 11:23 UTC, Kleidukos commented on cabal-install/src/Distribution/Client/Nix.hs
> +      print "You can learn more about it here: https://cabal.readthedocs.io/en/latest/nix-integration.html"
Almost, the `warn` function introduces a `Warning: ` prefix already, so you can just write your message

2023-08-25 11:57 UTC, Kleidukos requested changes
QA notes are missing, and there is a redundant WARNING. Otherwise looks good.

2023-08-25 11:57 UTC, Kleidukos commented on cabal-install/src/Distribution/Client/Nix.hs
> +      warn verb "WARNING: Nix integration has been deprecated and will be removed in a future release."
Redundant "WARNING: ".

2023-09-01 09:26 UTC, Kleidukos requested changes

2023-09-01 09:26 UTC, Kleidukos commented on doc/nix-integration.rst
> +    The original mechanism can still be easily replicated with:
```suggestion
    The original mechanism can still be easily replicated with the following commands:
```

2023-09-01 12:40 UTC, Kleidukos approved these changes

2023-09-01 12:41 UTC, Kleidukos commented
@yvan-sraka good job, now it's time to update the CLI output test suite and it should be good

2023-09-02 14:21 UTC, Kleidukos commented on cabal-testsuite/PackageTests/Freeze/enable-tests.out
looks like `enable-benchmarks.out` must also be edited. :)

2023-09-04 05:02 UTC, yvan-sraka commented
> @yvan-sraka good job, now it's time to update the CLI output test suite and it should be good

I updated the PR, now the tests are green :)

2023-09-06 09:36 UTC, merged