haddock-packages fixes
haskell/cabal pull request #9213
Opened 2023-08-27 09:48 UTC by coot

Cherry-picked commits from #8919.

@Mikolaj I asked in another PR but didn't got an answer if this will be accepted; I took a risk and created this PR.

2023-08-27 09:54 UTC, Kleidukos commented
@coot You didn't get a notification here? https://github.com/haskell/cabal/pull/9088#issuecomment-1693896825

2023-08-27 10:33 UTC, Kleidukos requested changes

2023-08-27 10:33 UTC, Kleidukos commented on cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.out
> +Documentation created: ../setup-external.dist/work/mysql/dist/doc/html/mysql
this should be `mysql/` right?

2023-08-27 13:08 UTC, coot commented
@Kleidukos it was [here](https://github.com/haskell/cabal/pull/9207#issuecomment-1693866800).

2023-08-27 13:09 UTC, coot commented on cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.out
> +Documentation created: ../setup-external.dist/work/mysql/dist/doc/html/mysql
I think you're right.

2023-08-27 13:15 UTC, Kleidukos commented
@coot yes sorry, I meant to ping you there to show you that it was quite hard to get this fix backported. But perhaps this PR will be more lucky! :)

2023-08-27 13:44 UTC, coot commented
Yes, it wasn't easy because of the style changes that got in the way :grin:.

2023-08-27 14:02 UTC, Kleidukos commented
@coot looks like we're not escaping this problem: https://github.com/haskell/cabal/actions/runs/5991249840/job/16249404279?pr=9213

2023-08-27 18:59 UTC, coot commented
It should be fixed now, I updated `pyyaml` to a newer version.

2023-08-27 19:30 UTC, Kleidukos commented
@coot It seems to me that the Whitespace check has failed, would you mind fixing that one? I'll merge your PR once my plane lands. :)

2023-08-27 23:04 UTC, Kleidukos approved these changes

2023-08-27 23:11 UTC, Kleidukos commented
@coot Dziękuję bardzo!

2023-08-27 23:38 UTC, merged

2023-08-28 09:18 UTC, Mikolaj commented
> @Mikolaj I asked in another PR but didn't got an answer if this will be accepted; I took a risk and created this PR.

Good call. Given the size, though, I'd test it especially hard in the alpha release and, if things don't play out, we can always revert before the release.

2023-08-28 18:42 UTC, coot commented
I tested `cabal hackage-project` command manually.  I will check it on a larger project too.