Fix run command environment
haskell/cabal pull request #9341
Opened 2023-10-15 18:48 UTC by xsebek

* reuse `withTempEnvFile` from `exec` command.
* closes #8391

---

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.

2023-10-15 18:58 UTC, geekosaur requested changes
A test and a `changelog.d` entry would be nice.

2023-10-15 18:58 UTC, geekosaur commented on cabal-install/src/Distribution/Client/CmdRun.hs
> +  , binDirectoryFor, pkgConfigCompiler
I think fourmolu wants this on a separate line like the others.

2023-10-15 19:03 UTC, xsebek commented
@geekosaur this is still a Draft PR and I am aware there will be more steps to get this merged. 🙂 

---

More importantly **this does not work** yet. Printing out the added environment shows just:
```Haskell
[("GHC_ENVIRONMENT",Just "/Users/xsebek/Git/haskell-language-server/dist-newstyle/tmp/environment.-20638/.ghc.environment.aarch64-darwin-9.2.8")]
```
The file does not exist, so I assume it's creation was skipped in `run`.

I would be grateful for any tips.

2023-10-16 01:08 UTC, gbaz commented
I think this PR is confused. env files are ghc package environment env files.

The ticket seems to be about just setting the PATH _shell environment_ variable -- a totally different usage of the name "environment".

The issue is that the test action is invoked via the `setup` wrapper, which sets that shell environment stuff automatically: https://github.com/haskell/cabal/blob/9f373253b9032ae32ead9f5ca17e49d192f9b8b9/cabal-install/src/Distribution/Client/ProjectBuilding.hs#L1798

(that in turn uses `withEnv` to set the path).

The run action is invoked directly, so doesn't have that logic, which will need to be shared/replicated.

2023-10-16 05:53 UTC, xsebek commented
@gbaz I overlooked where `exec` modifies PATH, it's here: 
https://github.com/haskell/cabal/blob/6ac9de412547c8321d28f7bf4d289e1b6323dcfb/cabal-install/src/Distribution/Client/CmdExec.hs#L168

2023-10-16 18:44 UTC, gbaz commented
Hrm... porting that from exec to run could likely work!

2023-10-21 21:06 UTC, xsebek commented
@gbaz please take a look now. 🙂

Not sure if there is a good place for `pathAdditions`/`binDirectories`, maybe the latter should go to `Distribution.Client.ProjectPlanning.Types`? Looking at it, there is `elabExeDependencyPaths` already... 🤔

2023-10-22 20:53 UTC, xsebek commented
I switched to using the existing `elabExeDependencyPaths` as it adds just what was explicitly required to PATH.

2023-10-23 00:38 UTC, gbaz approved these changes

2023-10-23 00:38 UTC, gbaz commented
Looks good, we should probably give it a user acceptance test at least.

2023-10-23 00:39 UTC, geekosaur approved these changes

2023-10-26 19:16 UTC, xsebek commented
@gbaz should I prepare something for the test or are the notes enough? 🙂

2023-11-03 13:31 UTC, mpickering commented
Can you please add a test?

2023-11-03 13:39 UTC, xsebek commented
@mpickering sure, I will get to it next week and see if there is a similar test that I could modify. 🙂

2023-11-11 13:38 UTC, xsebek commented
@mpickering as far as I can see, the only integration test that actually runs any `Cmd.*` action is `testHaddockProjectDependencies`. (I searched for `Cmd\S*\.\S*Action` in [test directory](https://github.com/haskell/cabal/blob/119c21b2b71f4bdc3b7461f1d75e17e1ebddb362/cabal-install/tests).) Am I missing something?

Reading the test [README](https://github.com/haskell/cabal/blob/dc6e1daa50a06c122d301402fb6e59692b80d633/cabal-install/tests/README.md) leaves me rather confused, as there are no shell scripts that run commands there.

Otherwise, I guess I could write an integration test for `elabExeDependencyPaths`, to see that it really gives the run command the paths to executable directories we would expect. 

There are "golden tests" in unit tests that check the cabal files in `cabal-install/tests/fixtures/init/golden/exe` which do contain `build-tool-depends`, but I am not sure if they test `elabExeDependencyPaths`. (I have no idea how much `mkStanza [mkExeStanza ...]` tests.)

2023-11-13 09:45 UTC, mpickering commented
@xsebek You should write a test in `cabal-testsuite/PackageTests` which directly ensures that running the sequence of commands in the ticket description works. 

I can write this test for you if you would like me to.

2023-12-20 14:54 UTC, ulysses4ever commented
@xsebek hey! Any news on this? The last bit remaining is a test. And Matt suggested he could do it for you if you’re having trouble. What do you think?

2024-01-08 20:09 UTC, jasagredo commented
I could absorb this PR into https://github.com/haskell/cabal/pull/9527. Thoughts? @ulysses4ever

2024-01-08 22:17 UTC, ulysses4ever commented
@jasagredo I'm good with absorbing!

2024-01-18 22:35 UTC, jasagredo commented
Closing as it was absorbed by #9527

2024-01-18 22:35 UTC, closed without merging