Fix the platform string for GNU/Hurd
haskell/cabal pull request #9434
Opened 2023-11-12 15:08 UTC by sthibaul

Since version 9.4.7-1, ghc fails to build on the GNU/Hurd port of Debian, see

https://buildd.debian.org/status/fetch.php?pkg=ghc&arch=hurd-i386&ver=9.4.7-1&stamp=1697717885&raw=0

Error, rule finished running but did not produce file:
  _build/stage0/lib/i386-gnu-ghc-9.4.6/ghc-boot-th-9.4.7/libHSghc-boot-th-9.4.7.a

and indeed, what did get produce was rather
_build/stage0/lib/i386-hurd-ghc-9.4.6/ghc-boot-th-9.4.7/libHSghc-boot-th-9.4.7.a (i386-hurd instead of i386-gnu).

This is due to confusion between hurd and gnu in various places.  Apparently previous versions of ghc were using gnu for the GNU/Hurd port, and thus putting libraries etc. in i386-gnu. So we have to follow the existing practice.

2023-11-12 15:17 UTC, Kleidukos approved these changes

2023-11-12 15:18 UTC, geekosaur approved these changes

2023-11-12 15:19 UTC, ffaf1 commented
https://github.com/haskell/cabal/blob/69417ac15c78a8c832ac256d6290064f9972526d/Cabal-syntax/src/Distribution/System.hs#L145-L156

I wonder whether this string should be changed too.

2023-11-12 15:23 UTC, ffaf1 approved these changes

2023-11-12 15:29 UTC, ulysses4ever commented
This PR looks like it tries to work around a problem with older GHCs (9.4.6 and previous, which all use "gnu" for GNU/Hurd). I'm not sure this is the direction we should go. Maybe we should rather strive to support newer GHCs in cabal's master branch?

2023-11-12 16:44 UTC, ffaf1 commented
Relevant gnu/hurd mentions I found in GHC codebase:
- [fptools_set_haskell_platform_vars.m4](https://gitlab.haskell.org/ghc/ghc/-/blob/master/m4/fptools_set_haskell_platform_vars.m4#L118-120)
- [ParseTriple.hs](https://gitlab.haskell.org/ghc/ghc/-/blob/master/utils/ghc-toolchain/src/GHC/Toolchain/ParseTriple.hs#L79)
- [ArchOS.hs](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/ghc-platform/src/GHC/Platform/ArchOS.hs#L160)

2023-11-12 18:13 UTC, sthibaul commented
> This PR looks like it tries to work around a problem with older GHCs (9.4.6 and previous, which all use "gnu" for GNU/Hurd). I'm not sure this is the direction we should go. Maybe we should rather strive to support newer GHCs in cabal's master branch?

Well, I'm fine with whatever you prefer, we "just" need a migration path. ATM I can't build debian's ghc 9.4.7 unpatched using debian's ghc 9.4.6, because the state is incoherent for now, the proposed fix is needed to get things coherent.

2023-11-13 18:03 UTC, Mikolaj commented
> Well, I'm fine with whatever you prefer, we "just" need a migration path. ATM I can't build debian's ghc 9.4.7 unpatched using debian's ghc 9.4.6, because the state is incoherent for now, the proposed fix is needed to get things coherent.

And you can't jump to 9.6.3 (assuming it's fixed there)?

2023-11-13 18:39 UTC, sthibaul commented
> And you can't jump to 9.6.3 (assuming it's fixed there)? {Edit: or wait for 9.4.8, assuming it will be fixed there?]

I can wait for 9.4.8, or build a patched 9.4.7, yes, but I don't understand what this changes in the problem. Perhaps what I don't actually understand is this:

> Maybe we should rather strive to support newer GHCs in cabal's master branch?

What do you mean by "newer" exactly? AIUI nothing has changed in ghc itself, it's just that as of its version 9.4.7-1 of the ghc packaging, debian started to use hadrian to build ghc packages, which probably changed which codepath actually does building/linking/installing, and AIUI it just happens that the codepath newly triggered has actually just always been bogus, and we just never noticed because it was never exercised. Thus why I'm here just proposing to fix it.

2023-11-13 19:54 UTC, Mikolaj commented
Oh, so it's not a bug in GHC?

2023-11-13 21:16 UTC, ulysses4ever commented
Another way to put my concern is that if this patch had

```haskell
ghcOsString Hurd = "hurd"
```

instead of what it currently has, I'd support it with no doubt.

2023-11-13 21:47 UTC, sthibaul commented
> Oh, so it's not a bug in GHC? [Edit: Meaning also the GHC build toolset.]

It has always be so in GHC.

> Another way to put my concern is that if this patch had
> 
> ghcOsString Hurd = "hurd"
>
> instead of what it currently has, I'd support it with no doubt.

It would be useless then... The whole point of these  lines is when the two parts don't actually match.

Put another way: in GHC's `m4/ghc_convert_os_m4`:

```
      gnu*) # e.g. i686-unknown-gnu0.9
        $3="gnu"
        ;;
```

is what matches the GNU/Hurd OS. Yes, a mere "gnu", because it's the pure-GNU OS as was planned by FSF decades ago. That's why various software call it just "gnu", when others prefer to all it "hurd", thus the confusing difference here.

Which is *exactly* the same kind of confusing terms as the other lines above the line I propose to change: depending who you ask, windows will rather be called mingw32, OS X will be called Darwin, Solaris will be called Solaris2. Those are exactly what GHC's `m4/ghc_convert_os_m4` matches, thus why I'm proposing to just follow what is already done for those.

2023-11-13 21:56 UTC, sthibaul commented
> in GHC's m4/ghc_convert_os_m4:
>
>      gnu*) # e.g. i686-unknown-gnu0.9
>        $3="gnu"
>        ;;

Put another way: autotools etc. call it "gnu", so I guess that's why the ghc port kept that name, so that ghc libraries get installed in i386-gnu-*, just like they are installed in i386-gnu by autotools etc. Turning that into i386-hurd could be more confusing when looking at the filesystem.

Another way would be to rename all "Hurd" occurrences in GHC into Gnu, but that would also bring confusion, this time to source readers, wondering whether it's GNU meaning GNU/Linux.

Thus why this correspondance, *exactly* like Windows is not really "mingw32", OSX is not really "darwin", Solaris is not only "solaris2", but it makes sense to keep both names and keep these lines to make the matching between the two.

2023-11-13 22:00 UTC, sthibaul commented
> > Oh, so it's not a bug in GHC? [Edit: Meaning also the GHC build toolset.]
> 
> It has always be so in GHC.

And things have *not* changed in GHC. It's just the Debian packaging that started using a different toolset, that seems not to know about the discrepancy between `hurd` and `gnu`.

2023-11-14 09:14 UTC, Mikolaj approved these changes
That's clarified for me now. Thank you.

2023-11-14 09:16 UTC, Mikolaj commented
BTW, when you are ready, please remove the needs-review label and add one of the merge labels, as explained in CONTRIBUTING.

2023-11-14 09:39 UTC, Mikolaj requested changes
Oh, and a changelog entry would be very welcome.

2023-11-14 16:29 UTC, Mikolaj approved these changes
Thank you very much!

2023-11-16 19:56 UTC, merged