`default-package-bounds` (RFC #9569) implementation
haskell/cabal pull request #9570
Opened 2023-12-27 13:47 UTC by jasagredo

Solves #8912 #9569 

# Manual QA

By adding a field `package-constraints` in a cabal file and a list of dependencies with version ranges, for each of those dependencies, any dependency declaration that was unbounded will be set to the one on `default-constraints`:

```
package-constraints:
  x > 5

library a 
  build-depends: x

library b 
  build-depends: x >5.5

library c
  build-depends: y
```

Should be understood as:

```
library a 
  build-depends: x >5

library b 
  build-depends: x >5.5

library c
  build-depends: y
```

If the stanza is omitted, then nothing changes wrt previous version.

Notice this should not influence:
- `build-tool-depends`
- `pkgconfig-depends`
- transitive dependencies

--------------------------------------------------

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

2023-12-28 12:18 UTC, michaelpj commented
- Why not apply to `build-tool-depends`? That seems surprising.
- What about subcomponent dependencies? i.e. `build-depends: foo:bar`. Will `default-package-bounds` apply there? I think it should, we should probably test this and maybe include it in the examples.

2023-12-28 15:22 UTC, jasagredo commented
1. `build-tool-depends` uses ExeDependency. But I think it should be doable.

2. When you say subcomponents you mean sublibraries right? I think you would have to restrict `foo` for now, but let me check.

2024-01-15 17:17 UTC, michaelpj commented
I don't know, it just seems like I would expect this to work:
```
default-package-bounds: tasty-discover < 3

test-suite a
  build-tool-depends: tasty-discover:tasty-discover
```
From a user perspective it looks just the same as `build-depends: foo:lib`

2024-01-15 17:18 UTC, michaelpj commented
just to reiterate that I continue to be excited about this feature :)

2024-01-15 17:21 UTC, jasagredo commented
Sounds reasonable but how do I disambiguate when parsing? I could create a new `AmbiguousDependency` which will be either an exe or a lib dependency and apply it wherever it seems it would fit.

2024-01-15 17:24 UTC, michaelpj commented
I don't actually know enough about cabal to say anything useful :sweat_smile:

2024-01-16 18:58 UTC, jasagredo commented
I could parse the following bounds:

```haskell
data DefaultBounds = DefaultBound    ShortText                       VersionRange
                   | DefaultExeBound PackageName UnqualComponentName VersionRange -- same as ExeDependency
```

And then apply the `DefaultBound` to `build-depends` and `pkg-config-depends` and the `DefaultExeBound` to `build-tool-depends`

2024-01-17 00:50 UTC, jasagredo commented
How does this look @michaelpj:

```cabal
cabal-version:      3.12
name:               foo
version:            0.1.0.0

default-package-bounds:
  , time <0
  , libpkgconf <0
  , bar:bar <0

flag build-depends-conflict
  manual: True
  default: False
  description: cause conflict

flag pkg-config-conflict
  manual: True
  default: False
  description: cause conflict

flag build-tool-conflict
  manual: True
  default: False
  description: cause conflict

library
  if flag(build-depends-conflict)
    build-depends:
      time
  else
    build-depends:
      time >0
  default-language: Haskell2010

  if flag(pkg-config-conflict)
    pkgconfig-depends: libpkgconf
  else
    pkgconfig-depends: libpkgconf >0

  if flag(build-tool-conflict)
    build-tool-depends: bar:bar
  else
    build-tool-depends: bar:bar >0
```

Note that the bounds are used here to make the compilation fail, to easily see that they are applied. And they only come to play if the specific cabal flag is enabled for the conflict. This is the test-case from the test I added.

So now it would apply to all `build-depends`, `pkgconfig-depends` and `build-tool-depends`

2024-01-17 09:32 UTC, michaelpj commented
That looks nice to me! I didn't know that `pkgconfig-depends` had bounds! OOI, can you put constraints on pkgconfig packages in `constraints`?

2024-01-17 16:32 UTC, jasagredo commented
No, constraints hold these:
```
data PackageConstraint = PackageConstraint ConstraintScope PackageProperty
data PackageProperty
   = PackagePropertyVersion   VersionRange
   | PackagePropertyInstalled
   | PackagePropertySource
   | PackagePropertyFlags     FlagAssignment
   | PackagePropertyStanzas   [OptionalStanza]
```
So it is only for Haskell package constraints

2024-01-17 16:33 UTC, jasagredo commented
However I just realized that you never asked for a way to provide default bounds for the pkgconfig libraries 😅 

Maybe this should only apply to `build-tool-depends` when qualified and to `build-depends` when qualified. Yes, I think that would be better

2024-01-17 16:52 UTC, michaelpj commented
I guess the intuition I want users to have is "this is a bit like what goes in `constraints`". Or at least, is a subset of that. That's true for the build-depends/build-tool-depends stuff, but would not be true for the pkgconf stuff it seems.

2024-01-17 17:05 UTC, jasagredo commented
Ok I removed the pkgconfig-depends altering via default-package-bounds

2024-01-18 19:16 UTC, jasagredo commented
Following up on the discussion on the Cabal meeting.

@gbaz: In [this comment](https://github.com/haskell/cabal/pull/9462#issuecomment-1831345325) you seem to agree to doing this on the solver (or at least say that it seems maybe reasonable) and @andreabedini's [concern](https://github.com/haskell/cabal/pull/9462#pullrequestreview-1754517331) about being faithful to what is written there sounds reasonable.

Anyways, lets revisit whether the way this is implemented looks right or not. @gbaz raised the point that any cabal-file-consumer that used to parse the dependency bounds from the files no longer would be able to do so.

2024-01-18 20:10 UTC, gbaz commented
Hrm. The trick I suppose is that we can't resolve the conditionals prior to the solver, because it will use them in backtracking. But we do need these bounds handled in the solver. So the solution seems to be that at the same step we "unpack" the conditionals into a flat list of possible dependencies, we also resolve this. And that's sensical. However, we have the issue that end-users still won't see the fully resolved deplist with bounds.

What I would suggest is then that just as the solver was modified to handle this sugar at the _same time_ as the conditionals, we also modify our standard conditional resolving things the same way.

In particular, we change the finalizePD and flatten functions to _also_ apply the default-package-bounds?

https://hackage.haskell.org/package/Cabal-syntax-3.10.2.0/docs/Distribution-PackageDescription-Configuration.html#v:finalizePD

2024-01-19 06:48 UTC, grayjay commented
> Hrm. The trick I suppose is that we can't resolve the conditionals prior to the solver, because it will use them in backtracking. But we do need these bounds handled in the solver. So the solution seems to be that at the same step we "unpack" the conditionals into a flat list of possible dependencies, we also resolve this. And that's sensical. However, we have the issue that end-users still won't see the fully resolved deplist with bounds.

This PR currently applies the default bounds during the conversion to the solver's index format at the start of solving, in `convCondTree`, not during the resolution of conditionals. The same logic could be applied before the solver. If I understand correctly, default bounds should be applied to all build-depends fields, regardless of whether they are under conditionals.

Another part of the ordering to consider is `--allow-newer`. Since this feature is like syntactic sugar, I would expect it to be applied earlier.

2024-06-09 16:23 UTC, jasagredo commented
I pushed a commit that makes sure this works with `allow-newer` too:
```
~/aa via λ 9.8.2 
❯ cat aa.cabal
cabal-version:      3.12
name:               aa
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Javier Sagredo
maintainer:         jasataco@gmail.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md
default-package-bounds:
  clock <0.1

library
    exposed-modules:  MyLib
    build-depends:    base ^>=4.19.1.0
                 , clock
    hs-source-dirs:   src
    default-language: Haskell2010

~/aa via λ 9.8.2 
❯ /home/javier/cabal/dist-newstyle/build/x86_64-linux/ghc-9.8.2/cabal-install-3.13.0.0/x/cabal/build/cabal/cabal build --dry-run                     
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: aa-0.1.0.0 (user goal)
[__1] next goal: clock (dependency of aa)
[__1] rejecting: clock-0.8.4 (conflict: aa => clock<0.1)
[__1] skipping: clock; 0.8.3, 0.8.2, 0.8, 0.7.2, 0.7.1.1, 0.7.1, 0.6.0.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0.1, 0.5.0.0, 0.4.6.0, 0.4.5.0, 0.4.4.0, 0.4.3.0, 0.4.2.0, 0.4.1.3, 0.4.1.2, 0.4.1.1, 0.4.0.1, 0.3, 0.2.0.0, 0.1.2.1, 0.1.2, 0.1.1, 0.1 (has the same characteristics that caused the previous version to fail: excluded by constraint '<0.1' from 'aa')
[__1] fail (backjumping, conflict set: aa, clock)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: aa, clock


~/aa via λ 9.8.2 
❯ /home/javier/cabal/dist-newstyle/build/x86_64-linux/ghc-9.8.2/cabal-install-3.13.0.0/x/cabal/build/cabal/cabal build --dry-run --allow-newer
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Build profile: -w ghc-9.8.2 -O1
In order, the following would be built (use -v for more details):
 - aa-0.1.0.0 (lib) (first run)
```

2024-06-10 14:47 UTC, jasagredo commented
This seems to be ready to review and correct. @andreabedini pointed out that it is missing the features it brings if we use `Setup.hs`. He promised to explain me how `Setup.hs` works so that I can bring the feature there too :smile: .

2024-06-10 18:52 UTC, geekosaur requested changes

2024-06-11 06:51 UTC, jasagredo commented on doc/cabal-package-description-file.rst
> +        package-constraints:
Yeah, indeed. Good catches all of them. Thanks!!

2024-06-14 11:49 UTC, jasagredo commented on doc/cabal-package-description-file.rst
> +        build-depends: foo ==1.2.***
Remove this

2024-06-20 17:44 UTC, ulysses4ever commented
@andreabedini you opined on the initial RFC (#9477). Do you want to take a look at this?

2024-06-20 17:50 UTC, jasagredo commented
As I said in the meeting, @andreabedini mentioned in ZuriHac that "this will not work with Setup.hs". What did you mean exactly with that Andrea? I have never had to use `Setup.hs` so I don't know how it differs from normal `cabal`.

Also @grayjay mentioned (unless I misunderstood) in the meeting that this should probably be moved to Cabal-the-library. If you point me to a specific place I will be happy to explore it and try to move it there.

2024-06-21 08:38 UTC, mpickering commented
@jasagredo I think @andreabedini raises a good point. 

By `./Setup` interface he means if you compile a package using..

```
> cat Setup.hs
import Distribution.Simple; main = defaultMain
> ghc  Setup.hs
> /Setup configure
> ./Setup build
```

then will the default bounds apply? It sounded like in our conversation yesterday that the default bounds are only applied in the solver which is too late for this to work. Given they are working locally to a package it seems that modifying the bounds in `Cabal` library (in configure) could be an appropriate place. 

Does that make sense?

2024-06-21 09:16 UTC, jasagredo commented
Where can I read how `Setup` works and place it in my mental model on how cabal works? I have never had to use it ever (cabal has been able to always deal with whatever I needed to compile)

2024-06-21 09:32 UTC, michaelpj commented
So where's the point where this comes apart from normal `build-depends`? Do bounds in `build-depends` get checked by `Setup configure` but these won't be?

2024-06-21 10:03 UTC, jasagredo commented
These bounds are applied in the solver. However I don't seem to understand why `Setup` won't use the same path as the solver?

2024-06-21 10:06 UTC, geekosaur commented
The solver is part of `cabal-install`, not `Cabal`. It's inextricably linked to the store and to `pkg-config` among other things, none of which `Cabal` and therefore `Setup` know about.

2024-06-21 10:29 UTC, mpickering commented
See functions like `dependencySatisfiable` in `Distribution.Simple.Configure`.

2024-06-21 10:40 UTC, jasagredo commented
Is there a separate source tree used for Setup or is it intertwined with cabal code? Or does Setup only use Cabal and not cabal, and therefore I should find somewhere in Cabal to put this?

2024-06-21 10:43 UTC, mpickering commented
`./Setup` interface only uses code in `Cabal` library and its dependencies, it is completely distinct from `cabal-install`.

2024-06-25 04:19 UTC, andreabedini commented
@jasagredo I need to keep my promise! I'll reach out to you in private.

2024-06-26 08:13 UTC, andreabedini commented on doc/cabal-package-description-file.rst
> +
```suggestion
   ::

        default-package-bounds:
          markdown-unlit:markdown-unlit < 100

        build-tool-depends:
            markdown-unlit:markdown-unlit

      will be equivalent to:

   ::
   
        build-tool-depends:
            markdown-unlit:markdown-unlit < 100
```

2024-06-26 19:40 UTC, jasagredo commented
I have revamped this PR after talking to Andrea this morning. It is now a section. See the updated documentation.

2024-06-26 21:10 UTC, geekosaur approved these changes

2024-06-26 21:10 UTC, geekosaur commented on doc/cabal-package-description-file.rst
> +Notice only ``library a`` got its bounds modified. This process is only applied
```suggestion
Notice only ``library a`` had its bounds modified. This process is only applied
```
"Got" there seems a bit informal for formal documentation.

2024-06-26 21:10 UTC, geekosaur commented on doc/cabal-package-description-file.rst
> +as a syntactic desugar, only to avoid duplication and verbosity on the cabal
```suggestion
as a syntactic desugaring, only to avoid duplication and verbosity on the cabal
```

2024-06-26 21:10 UTC, geekosaur commented on doc/cabal-package-description-file.rst
> +in the same way as it is done for normal :pkg-field:`build-depends<None:build-depends>` dependencies.
```suggestion
in the same way as is done for normal :pkg-field:`build-depends<None:build-depends>` dependencies.
```

2024-07-01 07:13 UTC, grayjay reviewed
> Also @grayjay mentioned (unless I misunderstood) in the meeting that this should probably be moved to Cabal-the-library. If you point me to a specific place I will be happy to explore it and try to move it there.

I meant that the functionality to apply default bounds should be in Cabal (or Cabal-syntax) so that it can be used by Setup.hs, but it looks like the latest version of the code does that.

I didn't review the whole PR, but I have a few more comments from the code that I read while checking that.

2024-07-01 07:13 UTC, grayjay commented on Cabal-syntax/src/Distribution/PackageDescription/Configuration.hs
> +        Just db -> map (mapTreeConstrs (applyDefaultBoundsToDependencies db))
Why does `finalizePD` call `applyDefaultBoundsToBuildInfo` and `applyDefaultBoundsToDependencies` separately on the `CondTree`s, when the solver only calls `applyDefaultBoundsToCondTree`? I would have expected `Distribution.Types.DefaultBounds` to export only one function for applying default bounds and Cabal and the solver to each call it. That would help ensure that they both apply default bounds in the same way.

2025-01-01 19:51 UTC, ulysses4ever reviewed
I had a bunch of comments that I forgot to send, sorry!

2025-01-01 19:57 UTC, ulysses4ever commented
@grayjay could you maybe take another look at this PR? 

Anyone else? There was a lot of engagement in this thread (relatively) but reviews are still missing.

2025-01-01 20:00 UTC, jasagredo commented
There was a general rejection to this feature so I have no plans on improving this PR or the RFC. Sorry to make this explicit after you went through a review @ulysses4ever, I should have said it before.

2025-01-01 20:01 UTC, ulysses4ever commented
Ah, no worries, thanks for responding. Should we close it maybe?

2025-01-01 20:03 UTC, jasagredo commented
Yes, let's close it and the RFC.

2025-01-01 20:04 UTC, closed without merging