Add further tests of cyclical project imports
haskell/cabal pull request #9665
Opened 2024-01-27 20:11 UTC by philderbeast

While reviewing #9578, I saw that the cyclical test didn't `assertOutputContains` and had but one cyclical test, a simple loopback of a project importing itself. It now has the following test projects;

```
+-- cyclical-0-self.project (imports cyclical-0-self.project)
+-- cyclical-0-self.project (already processed)
+-- etc
```

```
+-- cyclical-1-out-back.project
 +-- cyclical-1-out-back.config (imports cyclical-1-out-back.project)
+-- cyclical-1-out-back.project (already processed)
 +-- etc
```

```
+-- cyclical-1-out-self.project
 +-- cyclical-1-out-self.config (imports cyclical-1-out-self.config)
 +-- cyclical-1-out-self.config (already processed)
 +-- etc
```

```
+-- cyclical-2-out-out-backback.project
 +-- cyclical-2-out-out-backback-a.config
  +-- cyclical-2-out-out-backback-b.config (imports cyclical-2-out-out-backback.project)
+-- cyclical-2-out-out-backback.project (already processed)
 +-- etc
 ```

+-- cyclical-2-out-out-back.project
 +-- cyclical-2-out-out-back-a.config
  +-- cyclical-2-out-out-back-b.config (imports cyclical-2-out-out-back-a.config)
 +-- cyclical-2-out-out-back-a.config (already processed)
  +-- etc

+-- cyclical-2-out-out-self.project
 +-- cyclical-2-out-out-self-a.config
  +-- cyclical-2-out-out-self-b.config (imports cyclical-2-out-out-self-b.config)
  +-- cyclical-2-out-out-self-b.config (already processed)
  +-- etc
```

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

2024-01-27 20:21 UTC, geekosaur requested changes

2024-01-27 20:21 UTC, geekosaur commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back-a.config
I think this file is missing a newline at the end?

2024-01-27 20:21 UTC, geekosaur commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back-b.config
Same here.

2024-01-27 20:21 UTC, geekosaur commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-backback-a.config
And here.

2024-01-27 20:21 UTC, geekosaur commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-backback-b.config
And here.

2024-01-27 20:21 UTC, geekosaur commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-self-a.config
And here.

2024-01-27 20:21 UTC, geekosaur commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-self-b.config
And here.

2024-01-27 20:27 UTC, philderbeast commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back-a.config
Easy to miss, sorry.

2024-01-27 20:27 UTC, philderbeast commented on cabal-testsuite/PackageTests/ConditionalAndImport/cyclical-2-out-out-back-a.config
Done.

2024-01-27 20:28 UTC, philderbeast commented
Thanks @geekosaur, I've added newlines where they were missing in all files.

2024-01-27 20:30 UTC, geekosaur approved these changes

2024-01-28 18:31 UTC, philderbeast commented
@Mikolaj if this gets approval, could we waive the 2 day delay please? It expands tests, tests that I help with #9578.

2024-01-29 13:25 UTC, philderbeast commented
Thanks @Mikolaj. I've squashed down to two commits, one that adds `assertOutputContains` to make the existing test more robust and another for adding the additional tests.

2024-01-29 17:31 UTC, merged

2024-01-29 17:31 UTC, philderbeast commented
Label merge+no rebase is necessary when the pull request is from an organisation.