Add a cabal target command
haskell/cabal pull request #9744
Opened 2024-02-26 19:39 UTC by philderbeast

Adds a `cabal target` command for showing targets that can be supplied to other commands like the `cabal build` command.

The initial motivation would have been #8953 but this is not a fix for that issue but it could be if the results are filtered. For example `lib` dependencies for `all:tests` are not filtered yet.

Related issues are #8683, #9732, #1382 and #4070.

I took the `cabal build` command and cut it short where it made a call to `printPlan`. The `cabal target` command calls `printPlanTargetForms` instead that is a modifiation of `printPlan`. Is there another way to get the targets (an easier way or a better way)?

Here's the help;

```
$ cabal --help
...
[running and testing]
  target                 List target forms within the project.
  list-bin               List the path to a single executable.
...
[new-style projects (forwards-compatible aliases)]
  v2-target              List target forms within the project.
  v2-build               Compile targets within the project.
...
```

The command specific help, a lot of which is taken straight from the user guide on [target forms](https://cabal.readthedocs.io/en/latest/cabal-commands.html#target-forms);

```
$ cabal target --help
List target forms within the project.

Usage: cabal target [TARGETS]

List targets within a build plan. If no [TARGETS] are given 'all' will be used
for selecting a build plan.

The given target can be;
- a package target (e.g. [pkg:]package)
- a component target (e.g. [package:][ctype:]component)
- all packages (e.g. all)
- components of a particular type (e.g. package:ctypes or all:ctypes)
- a module target: (e.g. [package:][ctype:]module)
- a filepath target: (e.g. [package:][ctype:]filepath)
- a script target: (e.g. path/to/script)

The ctypes can be one of: libs or libraries, exes or executables, tests,
benches or benchmarks, and flibs or foreign-libraries.

Flags for target:
 -h, --help                     Show this help text

Examples:
  cabal target all
    List all targets of the package in the current directory or all packages in the project
  cabal target pkgname
    List targets of the package named pkgname in the project
  cabal target ./pkgfoo
    List targets of the package in the ./pkgfoo directory
  cabal target cname
    List targets of the component named cname in the project
```

The command in action on the cabal project;

```
$ cabal target all
Resolving dependencies...
 - Cabal-QuickCheck:lib
 - Cabal-described:lib
 - Cabal-syntax:lib
 - Cabal-tests:lib
 - Cabal-tests:test:check-tests
 - Cabal-tests:test:custom-setup-tests
 - Cabal-tests:test:hackage-tests
 - Cabal-tests:test:no-thunks-test
 - Cabal-tests:test:parser-tests
 - Cabal-tests:test:rpmvercmp
 - Cabal-tests:test:unit-tests
 - Cabal-tree-diff:lib
 - Cabal:lib
 - cabal-benchmarks:test:cabal-benchmarks
 - cabal-install-solver:lib
 - cabal-install-solver:test:unit-tests
 - cabal-install:exe:cabal
 - cabal-install:lib
 - cabal-install:test:integration-tests2
 - cabal-install:test:long-tests
 - cabal-install:test:mem-use-tests
 - cabal-install:test:unit-tests
 - cabal-testsuite
 - hackage-security:lib
 - solver-benchmarks:exe:hackage-benchmark
 - solver-benchmarks:lib
 - solver-benchmarks:test:unit-tests
```

Notice that I'm not stripping out local dependencies that must also be build by the plan;

```
$ cabal run cabal -- target all:tests
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
 - Cabal-QuickCheck:lib
 - Cabal-described:lib
 - Cabal-syntax:lib
 - Cabal-tests:lib
 - Cabal-tests:test:check-tests
 - Cabal-tests:test:custom-setup-tests
 - Cabal-tests:test:hackage-tests
 - Cabal-tests:test:no-thunks-test
 - Cabal-tests:test:parser-tests
 - Cabal-tests:test:rpmvercmp
 - Cabal-tests:test:unit-tests
 - Cabal-tree-diff:lib
 - Cabal:lib
 - cabal-benchmarks:test:cabal-benchmarks
 - cabal-install-solver:lib
 - cabal-install-solver:test:unit-tests
 - cabal-install:lib
 - cabal-install:test:integration-tests2
 - cabal-install:test:long-tests
 - cabal-install:test:mem-use-tests
 - cabal-install:test:unit-tests
 - hackage-security:lib
 - solver-benchmarks:lib
 - solver-benchmarks:test:unit-tests
```

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added.

2024-02-26 19:51 UTC, fendor commented
Related PR: https://github.com/haskell/cabal/pull/7500

2024-02-26 20:32 UTC, philderbeast commented
Thanks for the link @fendor. I can see you've put a lot of effort into a larger scoped change.

2024-02-27 09:24 UTC, alt-romes commented
This looks plausible to me. We definitely need a test and changelog entry -- though I understand this only makes sense to do if the feature is generally agreed upon, which I can't guarantee by myself. I'll bring it up in the dev meeting later today.

2024-02-27 12:36 UTC, philderbeast commented
Because this uses `--dry-run` effectively, if dependencies haven't been built (I got there by changing branches, `cabal clean` won't invalidate already built dependencies) then these too will show up as targets.

```
$ cabal clean
$ cabal target all
Resolving dependencies...
 - Cabal-QuickCheck:lib
 - Cabal-described:lib
 - Cabal-syntax:lib
 - Cabal-tests:lib
 - Cabal-tests:test:check-tests
 - Cabal-tests:test:custom-setup-tests
 - Cabal-tests:test:hackage-tests
 - Cabal-tests:test:no-thunks-test
 - Cabal-tests:test:parser-tests
 - Cabal-tests:test:rpmvercmp
 - Cabal-tests:test:unit-tests
 - Cabal-tree-diff:lib
 - Cabal:lib
 - Cabal:lib
 - Diff:lib
 - OneTuple:lib
 - QuickCheck:lib
 - StateVar:lib
 - aeson:lib
 - ansi-terminal-types:lib
 - ansi-terminal:lib
 - ansi-wl-pprint:lib
 - assoc:lib
 - attoparsec:lib
 - attoparsec:lib:attoparsec-internal
 - base-compat:lib
 - base-orphans:lib
 - bifunctors:lib
 - bitvec:lib
 - bytestring-builder:lib
 - cabal-benchmarks:test:cabal-benchmarks
 - cabal-install-solver:lib
 - cabal-install-solver:test:unit-tests
 - cabal-install:exe:cabal
 - cabal-install:lib
 - cabal-install:test:integration-tests2
 - cabal-install:test:long-tests
 - cabal-install:test:mem-use-tests
 - cabal-install:test:unit-tests
 - cabal-testsuite
 - call-stack:lib
 - charset:lib
 - clock:lib
 - colour:lib
 - comonad:lib
 - contravariant:lib
 - data-default-class(lib:data-default-class)
 - data-fix:lib
 - dense-linear-algebra:lib
 - distributive:lib
 - dlist:lib
 - generically:lib
 - hackage-security:lib
 - happy:exe:happy
 - haskell-lexer:lib
 - indexed-traversable-instances:lib
 - indexed-traversable:lib
 - integer-conversion:lib
 - integer-logarithms:lib
 - math-functions:lib
 - mtl-compat:lib
 - mwc-random:lib
 - network-wait:lib
 - nothunks:lib
 - optparse-applicative:lib
 - parallel:lib
 - parsers:lib
 - pretty-show:lib
 - prettyprinter-ansi-terminal:lib
 - prettyprinter-compat-ansi-wl-pprint:lib
 - prettyprinter:lib
 - primitive:lib
 - regex-tdfa:lib
 - rere:lib
 - retry:lib
 - scientific:lib
 - semialign:lib
 - semigroupoids:lib
 - solver-benchmarks:exe:hackage-benchmark
 - solver-benchmarks:lib
 - solver-benchmarks:test:unit-tests
 - statistics:lib
 - strict:lib
 - tagged:lib
 - tasty-bench:lib
 - tasty-expected-failure:lib
 - tasty-golden:lib
 - tasty-hunit:lib
 - tasty-quickcheck:lib
 - tasty:lib
 - temporary:lib
 - text-iso8601:lib
 - text-short:lib
 - th-abstraction:lib
 - these:lib
 - time-compat:lib
 - transformers-compat:lib
 - tree-diff:lib
 - typed-process:lib
 - unbounded-delays:lib
 - unliftio-core:lib
 - unordered-containers:lib
 - uuid-types:lib
 - vector-algorithms:lib
 - vector-binary-instances:lib
 - vector-stream:lib
 - vector-th-unbox:lib
 - vector:lib
 - wherefrom-compat:lib
 - witherable:lib
```

2024-02-27 12:40 UTC, philderbeast commented
In investigating further, trying to build only the dependencies, I hit an error I've never seen before;

```
$ git rev-parse HEAD
6d9267d78b35c5075171309170825d42e4fd16e6

$ cabal build all --only-dependencies
Warning: this is a debug build of cabal-install with assertions enabled.
Error: [Cabal-7072]
Cannot select only the dependencies (as requested by the '--only-dependencies' flag),
the package Cabal-syntax-3.11.0.0 is required by a dependency of one of the other targets.
```

2024-02-28 10:52 UTC, andreabedini commented
Maybe `list-target(s)`? It seems to follow naturally from the help message:

```
target                 List target forms within the project.
list-bin               List the path to a single executable.
```

Let me emphasise that those are only the targets within the project (as the help already points out) and that different commands can interpret their arguments more liberally (e.g. any package-id is a valid target for `cabal install`).

2024-02-28 10:54 UTC, andreabedini commented
@philderbeast Ill give it a proper review ASAP

2024-02-28 13:38 UTC, philderbeast commented
> Maybe `list-target(s)`? It seems to follow naturally from the help message:
> 
> ```
> target                 List target forms within the project.
> list-bin               List the path to a single executable.
> ```
> 
> Let me emphasise that those are only the targets within the project (as the help already points out) and that different commands can interpret their arguments more liberally (e.g. any package-id is a valid target for `cabal install`).

I dislike the `list-bin` command name and wish it was named something else, like `bin-path`. I went with `target` because none of the other command names are plural. They're all verbs aren't they?

2024-02-28 16:29 UTC, michaelpj commented
What about `cabal target list`? There is [some consensus](https://clig.dev/#subcommands) that subcommands with the form `<cmd> <noun> <verb>` are the way to go. But then perhaps "target" is not a noun that we want to attach many verbs to :shrug:

2024-02-29 19:04 UTC, andreasabel commented
Can we have a `cabal list` command that allows subcommands that all display some information about what cabal thinks about the world?
- `cabal list targets`  This PR.
- `cabal list bins` Alt. name of `cabal list-bin`.
- `cabal list paths` Alt. name of `cabal path`.
- etc.

2024-02-29 19:15 UTC, philderbeast commented
> What about `cabal target list`?

Yes @michaelpj a subcommand instead is a possibility. As implemented this is acting as `cabal build --dry-run` but printing something different at the end, printing the targets rather than what would be built.

2024-02-29 19:26 UTC, geekosaur approved these changes

2024-03-05 21:02 UTC, Mikolaj commented
I like `cabal build --print-targets`, because then we don't have to think whether it's going to be used a lot or only in very special circumstances (a top-level command would probably require establishing it's going to be used often enough). Maybe let's make it even more non-intrusive (though harder to use) and let `cabal build --print-targets` really build and then print the built targets (or separately the targets that are built and the targets that could be built) and `cabal build --dry-run --print-targets` show only all the possible targets? That's a more radical interpretation of your "but printing something different at the end" (or maybe it's "and printing some extra info at the end"). Makes sense? Then it's even more fine if the result with and without `--dry-run` or with and without stuff already built differs (cabal commands are stateful).

2024-03-05 23:36 UTC, philderbeast commented
I favour `--print-targets` too. Saw that this is a new make option;

> As of Jan 8th, 2024, Make has a --print-targets option that should do this properly without hacky regexes. The current version is Make 4.4.1 so the next release after that will have this feature.
SOURCE: [How do you get the list of targets in a makefile?](https://stackoverflow.com/questions/4219255/how-do-you-get-the-list-of-targets-in-a-makefile/41490195#41490195)

2024-03-06 08:49 UTC, michaelpj commented
-1 for attaching this to `cabal build`

- Sometimes you don't want to build! Now you need `cabal build --dont-build --print-targets`. Yes, we already have `--dry-run`, but that's supposed to tell you what it was going to build, so how are we going to glue the output together? Awkward. It's just generally difficult making a command do double duty.
- Most importantly, the targets are _not_ uniquely associated with building. You can also use them in `repl` and many other commands. So do we add `cabal repl --print-targets` too? It's just not a build thing. In contrast, `--dry-run` tells you what would have been _built_, so really does make sense to belong to `cabal build`.

Make is different because a) it doesn't have sub-commands and b) the only operation on targets is building them.

Food for thought: https://doc.rust-lang.org/cargo/commands/cargo-metadata.html

2024-03-06 13:55 UTC, philderbeast commented
My main motivation for this change, no matter which command or subcommand or option we put it under, is to help interactive use of cabal itself and not for producing a machine readable format for IDE tooling like the `cabal status` enchancement of #7500. Lots of commands take targets. This change shows me those targets.

2024-03-17 15:26 UTC, philderbeast commented
> perhaps `cabal project targets` could be nice?

We have targets when there is no actual project file, when there is just a `.cabal` file.

2024-03-17 15:28 UTC, philderbeast commented
> * Most importantly, the targets are _not_ uniquely associated with building.

So a top-level `targets` command makes sense, not subordinate to some other command.

2024-03-17 15:32 UTC, philderbeast commented
> What about `cabal target list`?

What else would we do with targets rather than list them? Perhaps we should pluralize it as `cabal targets`. We asking them to identify themselves with this command.

2024-05-01 10:31 UTC, Mikolaj commented
Let's keep discussing this. Does anybody remember the conclusions of the discussion of the command names (related to `cabal path`, but also more general) we had at the open fortnightly cabal devs meeting recently?

2024-05-06 18:42 UTC, philderbeast commented
> Can we have a `cabal list` command that allows subcommands that all display some information about what cabal thinks about the world?
> 
> * `cabal list targets`  This PR.
> * `cabal list bins` Alt. name of `cabal list-bin`.
> * `cabal list paths` Alt. name of `cabal path`.
> * etc.

@andreasabel are you suggesting we keep `cabal target` but also add `cabal list targets`?

```diff
    $ cabal list targets --help
    Target disclosure and synonym of command 'cabal target'.

-   Usage: cabal target [TARGETS]
+   Usage: cabal list targets [TARGETS]

    Reveal the targets of build plan. If no [TARGETS] are given 'all' will be used
    for selecting a build plan.

    A [TARGETS] item can be one of these target forms;
    - a package target (e.g. [pkg:]package)
    - a component target (e.g. [package:][ctype:]component)
    - all packages (e.g. all)
    - components of a particular type (e.g. package:ctypes or all:ctypes)
    - a module target: (e.g. [package:][ctype:]module)
    - a filepath target: (e.g. [package:][ctype:]filepath)
    - a script target: (e.g. path/to/script)

    The ctypes can be one of: libs or libraries, exes or executables, tests,
    benches or benchmarks, and flibs or foreign-libraries.

    Flags for target:
    -h, --help                     Show this help text

    Examples:
-   cabal target all
+   cabal list targets all
        Targets of the package in the current directory or all packages in the project
-   cabal target pkgname
+   cabal list targets pkgname
        Targets of the package named pkgname in the project
-   cabal target ./pkgfoo
+   cabal list targets ./pkgfoo
        Targets of the package in the ./pkgfoo directory
-   cabal target cname
+   cabal list targets cname
        Targets of the component named cname in the project
```

2024-06-27 03:26 UTC, andreabedini requested changes
If you want to obtain list the targets you probably do not need all most of `targetAction`.

`withContextAndSelectors` is what powers `cabal run myscript.hs` unless you want to support `cabal target myscript.hs` you won't need it. If you do not use it, `cabal target` will only work in a project context. This is what I would expect.

`runProjectPreBuildPhase` rebuilds the project plan and then uses the function you pass to trim it down to only the required targets. Again, if you just want to list the available targets, you don't need to trim anything. Also it marks the up-to-date targets as 'installed', which means you won't get them from `InstallPlan.executionOrder`.

Assuming I understand what you want to do, I think you need to:

- use `establishProjectBaseContext` to read the project configuration
- use `rebuildInstallPlan` to get the full plan
- use `readTargetSelectors` to parse the target selector strings on the command line into a list of `TargetSelector`
- use `resolveTargets` to resolve those target selectors against the plan

This gives you a `TargetsMap` associating each unit in the plan with a list of components and the matched selectors.

```
type TargetsMap = Map UnitId [(ComponentTarget, NonEmpty TargetSelector)]
```

I guess this is want you might want to display. You might need to lookup the unit ids in the plan again though, which is a bit annoying.

I hope I didn't misunderstood what you are trying to do.

2024-12-31 13:07 UTC, philderbeast commented
Thanks @andreabedini. I followed your outline for a simpler implementation. I have some tidying up around the edges to do but I am happy with how it is going.

```
$ cabal run cabal-install:exe:cabal -- target all:exes
...
Fully qualified target forms:
 - buildinfo-reference-generator:exe:buildinfo-reference-generator
 - cabal-install:exe:cabal
 - cabal-testsuite:exe:cabal-tests
 - cabal-testsuite:exe:setup
 - cabal-testsuite:exe:test-runtime-deps
 - cabal-validate:exe:cabal-validate
 - solver-benchmarks:exe:hackage-benchmark
```

2025-01-01 14:24 UTC, philderbeast commented on cabal-install/src/Distribution/Client/CmdTarget.hs
> +  withContextAndSelectors RejectNoTargets Nothing flags targetStrings globalFlags BuildCommand $ \targetCtx ctx targetSelectors -> do
Thanks for the explanation @andreabedini. I'm not using `withContextAndSelectors` any more.

2025-01-01 16:25 UTC, philderbeast commented on cabal-install/src/Distribution/Client/ProjectOrchestration.hs
> +printPlanTargetForms
Thanks @andreabedini for showing that `zlib:lib` was not a valid target. I've removed this function and added question #10695.

2025-01-03 15:14 UTC, Kleidukos requested changes

2025-01-03 15:14 UTC, Kleidukos commented on cabal-install/src/Distribution/Client/CmdTarget.hs
> +    , commandSynopsis = "Disclose selected targets."
"Disclose" means "to reveal information that was previously hidden / kept secret". I don't think this is the correct word. `Display` or `print` would be better fits.

2025-01-04 13:09 UTC, philderbeast commented on cabal-install/src/Distribution/Client/CmdTarget.hs
> +    , commandSynopsis = "Disclose selected targets."
Both display and print are very generic.

> disclose:
> To uncover and expose to view (anything material); to remove a covering from; to reveal, allow to be seen.
> SOURCE: [OED, disclose](https://www.oed.com/dictionary/disclose_v?tl=true)

2025-01-04 17:21 UTC, philderbeast commented on cabal-install/src/Distribution/Client/CmdTarget.hs
> +    , commandSynopsis = "Disclose selected targets."
I've changed the synopsis to use target as a verb:

```diff
-    , commandSynopsis = "Disclose selected targets."
+    , commandSynopsis = "Target a subset of all targets."
```

2025-01-07 22:32 UTC, Kleidukos commented on cabal-install/src/Distribution/Client/CmdTarget.hs
> +    , commandSynopsis = "Disclose selected targets."
@philderbeast Yes they are very generic, because we are doing a generic operation. We are not exposing to view something previously hidden, as is the meaning of disclose. :)

Actually I much prefer how you phrased it in the description of the PR:

> showing targets that can be supplied to other commands

If you could change the other instances of `disclose` that would be grand. This is my only remark regarding this PR. :)

2025-01-09 20:50 UTC, philderbeast commented
@Kleidukos I've brought the user guide docs up to date with the `--help` docs. There's no mention of disclosing anything ;-)

2025-01-10 11:44 UTC, Kleidukos approved these changes

2025-01-10 11:44 UTC, Kleidukos commented on changelog.d/pr-9744.md
> +Adds a `cabal target` command for discovering, disclosing and checking selected
You missed that one ;)

2025-01-10 11:44 UTC, Kleidukos commented
@philderbeast That's the last thing on my part, I'm pre-emptively approving.

2025-01-10 12:05 UTC, philderbeast commented on changelog.d/pr-9744.md
> +Adds a `cabal target` command for discovering, disclosing and checking selected
Oops, fixed now.

2025-01-11 19:22 UTC, philderbeast commented
@mpilgrem this is similar to [stack ide targets](https://github.com/commercialhaskell/stack/pull/6126) that I added in May 2023. Instead of taking explicit `--exes`, `--tests` and `--benches` options to select the target subset, I'm able to reuse [target forms](https://cabal.readthedocs.io/en/latest/cabal-commands.html#target-forms) and select more varied and finer-grained target subsets than `stack ide targets` can. Most `cabal-install` commands are active verbs, `init`, `configure`, `freeze`, `build`, `check` etc so I went with "target" as the command name. I also prefer the command to be at the top level for discoverability rather than a subcommand. Many other commands take `[TARGETS]` so they're import to know about.

2025-01-13 23:52 UTC, philderbeast commented
@geekosaur you approved the cut down build implementation on Feb 29, 2024. The newer implementation is better. Care to take another look?

2025-01-14 00:50 UTC, geekosaur approved these changes

2025-01-14 00:50 UTC, geekosaur commented on cabal-install/src/Distribution/Client/CmdTarget.hs
> +        \ will *only* show 'libs' and 'exes' of the [TARGETS]. To also show \
```suggestion
        \ will only show 'libs' and 'exes' of the [TARGETS] by default. To also show \
```
The emphasis seemed a bit strong, especially given that it's effectively denied by the continuation.

2025-01-14 00:50 UTC, geekosaur commented on doc/cabal-commands.rst
> +    **only** show ``libs`` and ``exes`` of the ``[TARGETS]``. To also show tests and
Same thing here.
```suggestion
    only show ``libs`` and ``exes`` of the ``[TARGETS]`` by default. To also show tests and
```

2025-01-14 01:08 UTC, philderbeast commented
Label merge+no rebase is necessary when the pull request is from an organisation.

2025-01-14 22:38 UTC, mpilgrem commented
As a brief aside, in my view, the Stack 'information' UI is suboptimal (i.e. not to be emulated) but the 'costs' of getting to a better UI would outweigh the relative benefits of the end point. If `stack ls` is about Stack itself and `stack query` is about 'the build', and I could start from scratch, I would change `stack ide targets` to `stack query targets` and `stack ls dependencies` to `stack query dependencies`.

2025-01-16 03:09 UTC, philderbeast commented
@mergify refresh

2025-01-16 11:22 UTC, philderbeast commented
@mergify refresh

2025-01-16 11:28 UTC, philderbeast commented
@Mikolaj this one has been "ready and waiting" longer than I'd expect.

2025-01-16 11:37 UTC, Mikolaj commented
It says the label was auto-assigned "2 days ago", so maybe it's fine. Let's monitor...

2025-01-16 11:37 UTC, Mikolaj commented
@mergify queue

2025-01-16 11:40 UTC, Mikolaj commented
@mergifyio unqueue

2025-01-16 11:40 UTC, Mikolaj commented
@mergifyio requeue

2025-01-16 11:43 UTC, Mikolaj commented
@Mergifyio requeue

2025-01-16 11:44 UTC, Mikolaj commented
Hmm, strange, it says "This pull request is already queued", but the queue is empty. But maybe that's normal for no-rebase PRs. Let's give it some time.

2025-01-16 11:52 UTC, philderbeast commented
> It says the label was auto-assigned "2 days ago", so maybe it's fine. Let's monitor...

Thanks for taking a look and nudging it forward. Hovering over the "2 days ago" label shows the exact time.

2025-01-16 12:27 UTC, merged

2025-01-16 12:29 UTC, Mikolaj commented
No idea what it was, but manually applying label merge_delay_passed fixed it. I'm a bit lost on whether merge_delay_passed is superseded by ready_and_waiting and, if not, why it wasn't auto-applied here.

2025-01-16 12:29 UTC, geekosaur commented
`merge+no rebase` doesn't use the queue AIUI.

Note that it says [above](https://github.com/haskell/cabal/pull/9744#issuecomment-2595290407) "`pull request branch update failed`".

2025-01-16 12:30 UTC, geekosaur commented
`ready and waiting` doesn't mean `merge delay passed`, it means we're in the cool-down period.