Text file, newlines at end of files
haskell/cabal pull request #9804
Opened 2024-03-13 21:13 UTC by philderbeast

Fixes #9802 for `*.hs` and `*.project` files and adds a script taking a file glob pattern for doing this, adding newlines at the ends of files where needed.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

2024-03-13 21:37 UTC, geekosaur approved these changes

2024-03-13 22:13 UTC, ffaf1 commented
@andreasabel created `whitespace.yml`, let us see what he has to say.

2024-03-14 11:27 UTC, philderbeast commented
@ulysses4ever I see you are a [fix-whitespace contributor](https://github.com/agda/fix-whitespace/graphs/contributors). Do you think we can get `fix-whitespace` and `fourmolu` to play nicely together?

2024-03-14 16:18 UTC, geekosaur approved these changes

2024-03-14 16:18 UTC, geekosaur commented on doc/getting-started.rst
> +To run the executable, switch into the application directory with ``cd myapp`` and  run
```suggestion
To run the executable, switch into the application directory with ``cd myapp`` and run
```

2024-03-15 06:34 UTC, andreasabel approved these changes
You could also use https://github.com/andreasabel/fix-whitespace-action:
```yaml
steps:
- uses: actions/checkout@v4
- uses: andreasabel/fix-whitespace-action@v1
```
This action downloads the pre-build binary of `fix-whitespace` and runs it, and also caches it.

2024-03-15 10:16 UTC, philderbeast commented
Thanks @andreasabel `fix-whitespace-action` is way less configuration. I reverted one of the corrections and it shows violations in the output.

2024-03-15 10:17 UTC, philderbeast commented
Label merge+no rebase is necessary when the pull request is from an organisation.

2024-03-15 10:22 UTC, ulysses4ever requested changes
Instead of creating a separate workflow, can we add it to the quick-jobs workflow?

Can you check that fix-whitespace is run with a flush that will show the actual violations?

2024-03-15 10:27 UTC, philderbeast commented
> I reverted one of the corrections and it shows violations in the output.

@ulysses4ever I checked and it shows violations.

2024-03-15 10:28 UTC, ulysses4ever commented
Very cool, thanks!

2024-03-15 10:30 UTC, philderbeast commented
@ulysses4ever, funny thing about moving it to quick jobs is that it now doesn't run quite as quickly!

2024-03-15 10:33 UTC, philderbeast commented
In terms of developer feedback, putting it alongside (at the end of) quickjobs is a big degradation.

2024-03-15 10:34 UTC, ulysses4ever commented
Mm, good point. My intention was not having it run quickly, though, and rather I dislike proliferation of standalone workflows. But maybe it’d be good to get an actually quick feedback from this job…

We need to fix quick-jobs to only download binaries and not build anything with ghc!

2024-03-15 10:34 UTC, ulysses4ever approved these changes

2024-03-15 10:35 UTC, philderbeast commented
I do think that jobs like this one and the docs should run near instantly otherwise the wait is annoying.

2024-03-15 10:37 UTC, philderbeast commented
@ulysses4ever are you OK if I revert the last change, putting whitespace into its own workflow?

2024-03-15 10:38 UTC, ulysses4ever commented
Yeah, up to you, approved. Thanks!

2024-03-15 10:40 UTC, philderbeast commented
@ulysses4ever I see there is something wrong with the cache in [quick jobs](https://github.com/haskell/cabal/actions/runs/8294806206/job/22700513058?pr=9804);

> Post job cleanup.
> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist,
> hence no cache is being saved.

2024-03-15 11:25 UTC, ulysses4ever commented
Interesting... Maybe with a new ticket with the continuous-integration label.

2024-03-16 11:35 UTC, philderbeast commented
How much squashing should I be doing with this given that the advice is:

> If you push a fix of a whitespace violation, please do so in a _separate commit_.

2024-03-18 11:35 UTC, merged

2024-03-25 17:47 UTC, philderbeast commented
Sorry @Mikolaj for the lack of squashing. I asked about squashing but forgot to come back to it. Noticed when I got the cabal.head email.

2024-03-26 08:55 UTC, Mikolaj commented
Ouch. With no-rebase and no manual rebase nor squash just before merging, the 12 commits are strewn artistically across other PRs from the several last days. I guess we have to get used to git art. :D

2024-03-28 06:27 UTC, andreasabel commented
For the sake of bisecting, a linear history is really a plus.  Can't we enforce it on this repo?  (On the Agda repo, I disabled merge commits.)

2024-03-28 06:39 UTC, ffaf1 commented
Some contributors — and most importantly, some employers — do not fancy `cabal` to have write access their repos ([e.g.](https://github.com/haskell/cabal/pull/8981#issuecomment-1597278210)).

At first we did some [manual cherry-picking](https://github.com/haskell/cabal/pull/9051), but then we gave in and [`merge+no rebase` was introduced](https://github.com/haskell/cabal/pull/9427).

2024-03-28 07:20 UTC, andreasabel commented
Can mergify do the rebase by copying the contributor branch to a new branch on this repo first?  Can this be set up?  This might be a technical solution.

If a PR cannot be rebased then it should be rejected by default.  Otherwise, we'll not get a linear history. 

Contributors with write access could be encouraged to push to a branch here rather than on their own repo.

2024-05-13 15:19 UTC, ulysses4ever commented
@mergify backport 3.12

2024-05-13 18:53 UTC, ulysses4ever commented
@philderbeast 

>>   Can you check that fix-whitespace is run with a flag that will show the actual violations?

> I checked and it shows violations.

Apparently, we misunderstood each other. What I meant is that it should show not only the names of the files with whitespace issues but also the issues themselves. It could be done by the `verbose: true` option of the action: 

https://github.com/andreasabel/fix-whitespace-action/blob/2a7678e2f1319ae6e9595acb06b8cfb46e38af23/action.yml#L17-L20